### ISSUE TITLE
Remove log4j dependency

### ISSUE THREAD

**Issue by pgruetter** [smart-data-lake/smart-data-lake#10]
We should remove the log4j dependency completely. Apparently we still have it because it was used in a unit test. But on some systems we get problems if the dependency is declared with a scope "test" in maven, so it looks like it's used somewhere else as well.

**Comment by zzeekk** [comment]
Spark uses log4j 1.2, but we can exchange it to log4j 2.
This is working with #193. In my opinion this issue is fixed then.

@pgruetter, can you check please?
