### ISSUE TITLE
Dynamically add runId as DataFrame column / PartitionValue

### ISSUE THREAD

**Issue by zzeekk** [smart-data-lake/smart-data-lake#102]
**Is your feature request related to a problem? Please describe.**
SDLB now holds a runId tracking each start of an application. It is interesting to add runId as additional column in a DataFrame or as PartitionValue for traceability and partitioning.

**Describe the solution you'd like**
CustomTransformers can be used to add new columns to DataFrame. By feeding the runId (and maybe aswell attemptId and actionId) to options-Map parameter of the transform function, a runId column can be created easily. A predefined CustomTransformer which add's a runId-Column can be created.
I also suggest to extend the CustomTransformer interface with an additional function to transform PartitionValues. This is interesting if partitioning changes from e.g. days to month, and it can also be used to add runId value.

**Comment by zzeekk** [comment]
This should also support removing PartitionValues that should not propagated to the target.

**Comment by swissrussdev** [comment]
What about adding an "additional columns" parameter which we can extend to add additional metadata? We could implement the filename requirement over the same mechanism. Could be used to add additional runtime data to dfs?

**Comment by Geheiner** [comment]
I have two HiveTableDataObjects:

````
  int_dmd_gtg_strang {
    connectionId= stammdatenConnection
    path = "/DMD/data/gtg_strang"
    table {
      name = "~{id}"
    }
    type = HiveTableDataObject
    partitions = []
  }
````
and 

````
  int_dfz02_tls_events_detected_object = ${hiveTableTemplateInitial} {
    connectionId= inputConnection
    path = "/DFZ02/TLS/data/EVENTS_DETECTED_OBJECT"
    table {
      name = "~{id}"
    }
    type = HiveTableDataObject
      partitions = ["dt"]
  }
````
Both HiveTableObjects are partitioned by dt.
However, I'm telling the datalake only that int_dfz02_tls_events_detected_object is partitioned by dt, because I want it to load all partitions of int_dmd_gtg_strang.

When starting the smart-datalake with the option 
--partition-values dt=20200110
it currently filters the partitions for both dataObjects to dt=20200110.

So currently, it looks like It's not possible to filter partitionValues only on some data Objects.

Would this feature solve my Issue ?

**Comment by swissrussdev** [comment]
Afraid not! If the tables are partitioned and you specify a valid partition filter it will be used on all objects. I think you'd have to use separate feeds for that. Depending on your exact use case there may be other options. Otherwise it's a new feature request - sorry!

**Comment by Geheiner** [comment]
all right, thanks, then I open up a new one for this
