### ISSUE TITLE
Historisation fails when null values are interchanged

### ISSUE THREAD

**Issue by swissrussdev** [smart-data-lake/smart-data-lake#110]
**Describe the bug**
The hashing mechanism operates on a string generated from the non-null Row values. A change in a record from "A", null, "B" to "A","B",null will therefore not be updated correctly.

**To Reproduce**
Unit test to be provided in PR.

**Expected behavior**
Changes in position of null values should cause a new historized record to be generated.

**Additional context**
Adding Schema Information to the Hash would make it more robust.

**Comment by zzeekk** [comment]
Hello @swissrussdev, i also wondered about exluding null columns for hash calculation. In another project we use the following udf for calculating a hash for a Row:
`val udf_hash:UserDefinedFunction = udf((row: Row) => row.hashCode)`

**Comment by swissrussdev** [comment]
Hi @zzeekk - thanks. Since the hash has to be calculated over a subset of columns, we don't always have a Row to work with. However, I've pushed a proposed solution, which incorporates the schema in the hash, allows for hashing on column subsets and also eliminates the need for a udf. Let me know what you think
