### ISSUE TITLE
CustomSparkAction doesn't choose mainInput if multiple inputs are partitioned

### ISSUE THREAD

**Issue by zzeekk** [smart-data-lake/smart-data-lake#116]
**Describe the bug**
CustomSparkAction doesn't choose mainInput if multiple inputs are partitioned, because decision is ambiguous.

**To Reproduce**
Create a CustomSparkAction with multiple partitioned input DataObjects.

**Expected behavior**
Take the first partitionend input as mainInput and write a log message about the decision.

**Comment by pgruetter** [comment]
@zzeekk : I linked #124, this one is included there, correct?

**Comment by zzeekk** [comment]
> @zzeekk : I linked #124, this one is included there, correct?

Yes, thanks!
