### ISSUE TITLE
init on an Action with breakDataframeLineage=true should also work when the HiveTable does not exist

### ISSUE THREAD

**Issue by Geheiner** [smart-data-lake/smart-data-lake#119]
**Describe the bug**
Given an Action that takes a HiveDataObject as input and for which you set breakDataframeLineage=true, when the table that corresponds to the HiveDataObject does not exist, then the init steps fails, complaining that the table does not exist.
The current behavior can be very confusing, since the error only occurs when the table does not exist. When the table exists, everything is fine.

**To Reproduce**
Create any Action taking a HiveDataObject as input, for which the table has not yet been created, and set breakDataframeLineage=true

**Expected behavior**

Probably the most intuitive behavior would be to not break the lineage at all during the init step if the table does not exist, and log a warning that breakDataLineage was overwritten to false during the init step because no data was found

**Comment by zzeekk** [comment]
added a unit test to branch feature/35-kafa-dataobject.

To support this SDL creates and passes on an empty dummy-DataFrame in init phase, just containing the schema, which is replaced in exec phase by the real fresh DataFrame read from the DataObject which now should be existing.
