### ISSUE TITLE
First-class support for acceptance testing

### ISSUE THREAD

**Issue by MarkusRothSBB** [smart-data-lake/smart-data-lake#120]
**Acceptance Tests for SDL**
Writing unit tests to test single transformations is easy. However, I can't find an easy and obvious way to write an integration or acceptance test that tests an entire ETL pipeline in an end-to-end fashion. Being able to write such tests in a simple and straight-forward fashion would enable an ATDD-approach in developing SDL applications, which I believe would be very beneficial.

**Requirements**
I want to write integration tests for SDL applications that do integration/end-to-end testing of an entire ETL pipeline. That means I want to use the configuration and custom transformations from my project, define a test input for all input dataObjects, define an expected output, and then write a simple assertion that the actual output is equal to the expected output. I want to use the real, productive configuration without any changes for the test.

I expect to test for errors such as:
- Joins that don't work due to duplicate column names
- Typos in dataObjects or actions
- Mismatch between names of dataObjects in the configuration and custom transformations
- Data type / schema mismatch between dataObjects
- Misunderstandings between different people regarding the expected behavior of the pipeline.

**Possible Solution**
I am not yet sure what a good way to implement this would be. A possible solution might be:

There is a new TestSmartDataLakeBuilder that takes the usual arguments parameter, as well as a Map[String, DataFrame] named overrideDataFrames. Whenever SDL wants to read data from a dataObject, it checks if the name of the data object is in the overrides. If it is, it returns the override dataFrame rather than reading from the actual dataObject. This way, the contents of the input-dataObjects can easily be constructed in Scala code in the test case.

TestSmartDataLakeBuilder needs to return a Map[String, DataFrame] containing all DataFrames of dataObjects that represent leaf nodes in the DAG. This way, they can easily be read to compare with expected values.

In such a scenario, a test HDFS filesystem can be used, for example with this: https://github.com/holdenk/spark-testing-base/wiki/HDFSCluster

There would need to be some way of preventing the test code to ever write to or read from real systems, maybe by requiring any dataObject that is not persisted on the (fake) HDFS cluster to be contained in overrideDataFrames?

**Better Ideas?**
This idea is not fully thought out yet, and maybe someone has already thought of something simpler? 

I would be happy to contribute to the development if we find a solution that makes sense to everyone.

**Comment by zzeekk** [comment]
Good suggestion. 

For #61/Recovery i already have a branch with part of the solution. There is a startRun method which takes initialSubFeeds as Parameters, and all SubFeed's of the run a collected in actionDAGRun.getRuntimeInfos. It could be used to get the calculated DataFrame's back.

What's missing is
a) a public interface to start a run: I suggest to add another method startRun(appConfig: SmartDataLakeBuilderConfig, initialSubFeeds: Seq[SubFeed]): Seq[SubFeed]
b) switch connections to the test environment: here i think it's important that your prod configuration supports switching environments, e.g. lab/app. This can be achieved by having a *.conf File with environment dependent configuration, e.g. mostly connections, which can be exchanged depending on the environment. Like this a HadoopFileConnection referencing your Prod Filesystem can be exchange to one referencing a local HDFS installation.

@MarkusRothSBB: Would do you think about this solution draft?

**Comment by pgruetter** [comment]
Interesting ideas, have to think about that some more. 
I'm note sure if overriding single DataObjects with manual dataframes is the most efficient way. I would try and think of way you can more easily simulate your whole pipeline by providing search-and-replace values. Some of it is already possible by using different connections as zzeekk has mentioned (remember that you can have a structure of configuration files). If you can replace values in all your paths / connections at once, you could simply switch to a testing environment. You could of course still create sample data just for these test cases, but have more options to do so.
We would still need the rest to get the dataframes of the leaf nodes and run asserts on them. And making sure nothing ever gets written to the actual production environment.

**Comment by MarkusRothSBB** [comment]
Hi guys, thanks for your well thought out  responses and being open to the idea!

**Test Input Insertion**
> For #61/Recovery i already have a branch with part of the solution. There is a startRun method which takes initialSubFeeds as Parameters,

So the solution would work like this: The test input is created as a partially completed initial run that is to be recovered from. All steps that read from input systems are marked as already completed, so that resuming from that state completes the other actions. I like it! As you mention, the challenge is how to make this easy to do in a Scala test case without hacking together state summary files manually.

**Test Output Extraction**
>  all SubFeed's of the run a collected in actionDAGRun.getRuntimeInfos. It could be used to get the calculated DataFrame's back.

Here I am not quite sure if the solution matches the acceptance testing use-case. I assume we would want to prevent the last step in the DAG from being executed. For example, if the last step is to write output data to a relational database, that step would fail during the test because of invalid connection values in the test configuration. That would lead to a failed run, which would presumably fail the test.
Instead, we want to read the dataFrame that _would_ be written to the final dataObject, not the result of actually having done so. Somehow, the action writing to a leaf dataObject in the DAG would have to understand that its target will never be read from and not write to it, instead returning the values it would have written to it to the test.
Maybe it might be easier to add a configuration option to actions that forces this behaviour during test runs? 

**Isolation**
> i think it's important that your prod configuration supports switching environments, e.g. lab/app.

> If you can replace values in all your paths / connections at once, you could simply switch to a testing environment.

This might get a bit fiddly, because we would need to handle input dataObjects, intermediate dataObjects and output dataObjects separately. Input and output objects would have to get dummy values, so that their real backing tables, web services or relational databases are never accessed. However, intermediate dataObjects must get replaced with paths to a local test system, so that their results can get written and read during the test. Of course, this is not a difference inherent in the design of SDL: Nothing prevents you from building a pipeline that uses an external relational database as an intermediate step.
In general though, I think this is a viable approach for now - maybe after having set this up for a couple of projects, a better solution will emerge.

> I would try and think of way you can more easily simulate your whole pipeline by providing search-and-replace values. 

I am note quite sure I understand all the details of this suggestion. @pgruetter, could be perhaps elaborate a bit more?

**Comment by pgruetter** [comment]
> > I would try and think of way you can more easily simulate your whole pipeline by providing search-and-replace values.
> 
> I am note quite sure I understand all the details of this suggestion. @pgruetter, could you perhaps elaborate a bit more?

Sure, I'll try ;-)
Let's say you read data for your pipeline from hdfs://nameservice/path/to/prod_data/ and have this path configured in various places in your configuration file.  
On the same nameservice you create a few very small objects that you want to use for integration tests, you place them on hdfs://nameservice/another/path/integration_data/. 
You should have a simple way of replacing "path/to/prod_data" with "another/path/integration_data".
Of course that's only one of the steps as mentioned by you above.

**Comment by MarkusRothSBB** [comment]
Thanks!

> On the same nameservice you create a few very small objects that you want to use for integration tests, you place them on hdfs://nameservice/another/path/integration_data/.

As far as I can tell, that only works for HDFS and similar file systems which can easily be replicated locally. You can't do that for an Oracle database, unless you somehow create a mock JDBC server in your test environment or something equally hacky. That's why I suggested being able to provide custom dataFrames as outputs of dataObjects - to skip the connection attempt to the system entirely.

**Comment by zzeekk** [comment]
Hi @MarkusRothSBB, 
we added a new possibilities for testing with PR #152, see also https://github.com/smart-data-lake/smart-data-lake/blob/develop/docs/Testing.md.
Please check how far your requirements are covered with this.

**Comment by MarkusRothSBB** [comment]
Hi @zzeekk, this is absolutely brilliant and exactly what I was looking for. I created a little wrapper around your example in Testing.md and can now write integration tests for an entire feed just as cleanly as unit tests for a single action. Much obliged, thanks for the amazing work.
