### ISSUE TITLE
acls of HiveTableConnections are ignored 

### ISSUE THREAD

**Issue by Geheiner** [smart-data-lake/smart-data-lake#128]
**Describe the bug**
When setting acls on the HiveTableConnections, the settings are ignored.
It only works if you set the acls directly on the HiveTableDataObject

**To Reproduce**
Try out any transformation with a HiveTableDataObject that uses a HiveTableConnection.
When you set the acls only on the HiveTableDataObject, the acls are set.
When you set the acls only on the HiveTableConnection, the setting is ignored and no acls are set
When you set them on both the HiveTableConnection and the HiveTableDataObject, only the acls of the HiveTableDataObject are taken into account.

````
  btlLayerConnection {
    type = HiveTableConnection
    db = ${conf.database.target}
    path-prefix = "hdfs://nameservice1/user/"${conf.database.target}"/datalake/btl"
    acl = {
      permission="rwxr-x----"
      acls = [{
        acl-type = "user"
        name = "impala"
        permission = "r-x"
      }]
    }
  }

  btl_dfz02_intermediate_positions_mapped = {
    type = HiveTableDataObject
    connectionId = btlLayerConnection 
    path = "/dfz02/intermediate/positions_mapped"
    table.name = "~{id}"
    acl = {
      permission="rwxr-x----"
      acls = [{
        acl-type = "user"
        name = "impala"
        permission = "r-x"
      }]
    }
  }
````

**Expected behavior**
The ACL Settings of HiveTableConnection should be taken into account, or the user should be forced to declare his ACLs only on the HiveTableDataObject.
If both are possible, it should be clarified which one wins if acls are set for both. In that case, it probably makes the most sense to say that the acls of the HiveTableDataObject override the acls of the HiveTableConnection 

**Additional context**

**Comment by swissrussdev** [comment]
Confirmed and also applies to Hadoop File Connection. Multiple references to the DO Parameter object but none to the connection.

**Comment by swissrussdev** [comment]
My bad - Hdfs ok. Hive and TickTock need fixing - on the case
