### ISSUE TITLE
Support Spark 3.0

### ISSUE THREAD

**Issue by pgruetter** [smart-data-lake/smart-data-lake#133]
**Is your feature request related to a problem? Please describe.**
Spark 3.0 was officially released, we should support the version.

**Describe the solution you'd like**
Update all libraries and test on Spark 3.0. 
After a quick test: Some rework needs to be done around metric logging as this has changed somewhat. 
Running on Databricks, some errors were thrown regarding multiple implementations of parquet, not sure if this is specific to Databricks though.

**Additional context**
If code changes are needed (especially around metric logging), we need to define on how to support both versions at the same time.

**Comment by zzeekk** [comment]
Spark 3 uses hadoop 2.7 (default) and has a profile to build for hadoop 3.2.
Spark3 doesnt support scala 2.11 anymore and scala 2.13 isn't yet supported - only scala 2.12 remains for now.

**Comment by zzeekk** [comment]
I have created directly a branch develop-spark3 with the changes for spark 3.0

SDL Version is 2.0.0-SNAPSHOT.
