### ISSUE TITLE
Action metrics check and fail

### ISSUE THREAD

**Issue by zzeekk** [smart-data-lake/smart-data-lake#142]
**Is your feature request related to a problem? Please describe.**
An Action might run successfully but with no data transfered because the input was empty. From a business perspective this might be a failure. It should be possible to define a metricsFailCondition, which is tested after execution of the action against their output metrics.

**Describe the solution you'd like**
New attibute metricsFailCondition allows to define a fail condition which is tested against output metrics. If condition is tested true, the action execution is failed with a new exception MetricCheckFailed.
The condition can be defined as Spark SQL expression and is tested against a local DataFrame created from all the outputs metrics. The DataFrame should have the following columns: dataObjectId, key, value. The metricsFailCondition is applied as where condition to this DataFrame.

**Comment by swissrussdev** [comment]
+1!
