### ISSUE TITLE
New creator: CustomFileCreator

### ISSUE THREAD

**Issue by frd0** [smart-data-lake/smart-data-lake#148]
**Is your feature request related to a problem? Please describe.**
The goal is to read from a custom source (e.g. REST API) and write into a file on HDFS (as a JSON file) as an initial step in the pipeline. 
Further down the pipeline the JSON file might be parsed and converted into a dataframe, using another feed potentially with a different lifecycle. 

The CustomDfCreator is allowing to implement a custom source. However, the sink of the method CustomDfCreator.exec is always a dataframe. This forces the implementation of the conversion into a dataframe in the custom creator already. 
Is there another way to store a plain file on HDFS, without converting to dataframe?

**Describe the solution you'd like**
Implement a "CustomFileCreator", allowing to implement a custom creator and an HDFS stream as an output. 

**Additional context**
CustomDfTransformer implements dataframe to dataframe. 
CustomFileTransformer implements HDFD to HDFS. 
CustomDfCreator implements custom source to dataframe.

**Comment by zzeekk** [comment]
Hi @frd0, thanks for the feature request. I agree that if we have a CustomDfCreator, we should also offer a CustomFileCreator. For now you have the option to create your own DataObject extending FileRefDataObject, see WebserviceFileDataObject (which actionally allows to query REST API's...)
