### ISSUE TITLE
Reference.md invalid link to API docs

### ISSUE THREAD

**Issue by kaelte** [smart-data-lake/smart-data-lake#16]
file `docs/Reference.md`:

API docs link `site/scaladocs/io/smartdatalake/workflow/connection/package.html` is not valid anymore.

**Comment by pgruetter** [comment]
This is a feature ;-)
We won't keep the API docs in the main branches (develop / master) because there's so many files. 
Instead, we only update the API docs in the gh-pages branch. That's also the branch used for the website.
