### ISSUE TITLE
Option to ignore missing partitions in DataObject

### ISSUE THREAD

**Issue by pgruetter** [smart-data-lake/smart-data-lake#166]
**Is your feature request related to a problem? Please describe.**
Let's say you have 2 main input systems for your pipeline. Data for system A goes back to 2010, system B only back to 2014. 
For initial loads you want to start data loads for the complete duration 2010 until today so you start with partition values 20100101 - today. 
This will currently fail with something like:

`assertion failed: (Action~reading_from_B) partitions ArrayBuffer(dt=20100101) missing for DataObject~dataobject_in_B`

**Describe the solution you'd like**
Add a configuration option to the DataObject to ignore validation of existing partitions.
If set, the action should not abort when there's missing partitions and just continue with the execution. No data is processed, but the action still succeeds.

**Additional context**
It's also important that the output of that action still creates the empty partitions. Otherwise you have problems when you have actions that combine data from system A and system B because one of the stage tables is missing some partitions.

**Comment by zzeekk** [comment]
I suggest to create an new configuration attribute expectedPartitionsCondition: Option[String]. It would take a Spark SQL expression which is evaluated against a partition definition (Seq[PartitionValues]) and returns true or false. Partition values where the condition is false are not checked if the exist in enrichSubFeedDataFrame.

**Comment by pgruetter** [comment]
That would work, yes 👍
