### ISSUE TITLE
deleteDataAfterRead fails with unmatched case exception

### ISSUE THREAD

**Issue by swissrussdev** [smart-data-lake/smart-data-lake#173]
**Describe the bug**
Setting deleteDataAfterRead=true causes an unmatched case exception.

e.g. `Unmatched case (CsvFileDataObject(DataObject~gugus-stg,/stage/gugus/raw,Map(quote -> ", header -> true, escape -> \, delimiter -> ;),List(),None,None,date,Overwrite,None,Some(AclDef(-rwxrwx---,Vector())),Some(Connection~hdfs),Some(sourcefile),None),InitSubFeed(DataObject~gugus-stg,List()))
`
**To Reproduce**
* Copy a csv file to a temporary directory
* Configure a CopyAction to copy the file to a target of your choice, set deleteDataAfterRead=true
* Run the Action

**Expected behavior**
Action should run und delete the input on success

**Additional context**
The Problem arises because CopyAction postExecSubFeed only works with SparkSubFeeds and not InitSubFeeds. I don't understand the messy details to know where the difference lies.

**Comment by pgruetter** [comment]
Hi @swissrussdev : What's the difference between this and #172  ? Only the example?

**Comment by swissrussdev** [comment]
None at all - got a github 404 after 172 and it spat me back to the bug form. Have closed it.
