### ISSUE TITLE
HiveTableDataObject: not new new path definition

### ISSUE THREAD

**Issue by kaelte** [smart-data-lake/smart-data-lake#195]
HiveTableDataObject loggs the following warning even when the feed is re-executed without any change:

`HiveTableDataObject:105 - Table XXX exists already with different path. The table will be written with new path definition hdfs://nameservice1/user/...!
`

It seems that the equality check does not work properly.

**Comment by kaelte** [comment]
https://github.com/smart-data-lake/smart-data-lake/commit/b6fee9d5559c72fa01b9239fba37c4f4350e70f7 Logging improved to see the issue:

... with different path /TABNAME/data
... with new path definition hdfs://nameservice1/user/USERNAM/stage/TABNAME/data

**Comment by pgruetter** [comment]
@kaelte This bug is fixed with #195, correct?

**Comment by zzeekk** [comment]
@pgruetter I guess you mean #196

**Comment by pgruetter** [comment]
> @pgruetter I guess you mean #196

Yes, sorry, I mean #196
