### ISSUE TITLE
Option to abort when Schema Evolution detected

### ISSUE THREAD

**Issue by pgruetter** [smart-data-lake/smart-data-lake#20]
We should offer an option to abort the execution whenever a schema evolution is detected.
Currently, if a schema evolution can be executed, it is done automatically. 

I can think of a few scenarios where this is not desired, especially in production environments. The schema evolution should then be executed in a controlled manner. 

It should still be easy to activate / deactivate schema evolution.

**Comment by zzeekk** [comment]
Implemented allowSchemaEvolution property for JdbcTableDataObject and DeltaLakeTableDataObject. Should we implement it aswell for HiveTableDataObject (only relevant with SaveMode.overwrite)?

**Comment by pgruetter** [comment]
IMHO, this would make sense, yes.

**Comment by pgruetter** [comment]
@zzeekk I don't see a need for this feature on HiveTableDataObject anymore. WDYT?

**Comment by zzeekk** [comment]
You're right, hive is no longer that important. No need to improve it.
