### ISSUE TITLE
Make recursiveInput optional

### ISSUE THREAD

**Issue by pgruetter** [smart-data-lake/smart-data-lake#202]
**Is your feature request related to a problem? Please describe.**
If you define a recursiveInputId in an action, the output is also available as input in your action. This DataObject is also ready and passed to your CustomTransformer and therefore, the DataObject needs to exist. 
On the very first run of an action, this criteria is not met (the DataObject was never written before) and the action fails. 

**Describe the solution you'd like**
I see two solutions:
- If the recursiveInput is not available, create an empty DataFrame with the given schema of the DataObject. Fail if no schema was defined (as it's probably too hard to evaluate the schema of the resulting DataFrame in the init phase where it's needed)
- Don't pass the recursiveInput to your transformer so you have the chance to check in your logic if the DataFrame was passed or not

**Additional information**
As workaround I just created an empty Hive table. SDLB reads the empty table, the action starts and schema evolution automatically creates the correct schema after the first run.

**Comment by mand35** [comment]
I experienced the same issue and can confirm, specifying schemaMin e.g. with `schemaMin =  "name1 STRING, _validFrom DATE, _validTo DATE, tariffDescriptor STRING " solved the issue.
