### ISSUE TITLE
Transitive dependency missing on classpath (eddsa-0.1.0.jar)

### ISSUE THREAD

**Issue by frd0** [smart-data-lake/smart-data-lake#207]
**Describe the bug**
Configuring an SFTP Connection leads to a ClassNotFoundException for a crypto library used in the standard DataObject. 
The required jar eddsa-0.1.0.jar is not delivered in the classpath of SDL. 

Manually adding the jar to the classpath solves the problem. 

**To Reproduce**
type = SFtpFileRefDataObject
connectionId = sftp

SDL v1.1.1

**Expected behavior**
Deliver all transitive dependencies

**Additional context**

**Comment by zzeekk** [comment]
Solved in release 1.2.0 / 2.0.0
