### ISSUE TITLE
Allow basic schema evolution for JdbcTableDataObjects

### ISSUE THREAD

**Issue by pgruetter** [smart-data-lake/smart-data-lake#216]
**Is your feature request related to a problem? Please describe.**
Currently, when an action writes data to a JdbcTableDataObjects it expects the table structure to match the structure of the DataFrame to be written. When adding or deleting columns, the target structure needs to be changed manually before executing SDL.

**Describe the solution you'd like**
If a schema evolution is detected, execute the necessary DDLs over JDBC automatically (i.e alter table add column, ...).

**Additional context**
- Of course under the assumption that the database user has the required permissions to do so
- Maybe it makes sense to deactivate the feature by default and only allow it to be overwritten in the config. Same goes for all schema evolutions, also unrelated to JdbcTableDataObjects.

**Comment by zzeekk** [comment]
Implementation suggestion by PR #389:
- Configuration flag allowSchemaEvolution with default false
- trait CanEvolveSchema to mark DataObject as able to evolve schema
- Implement adding new columns, set missing columns nullable and chaning datatypes if supported (checked by database)
