### ISSUE TITLE
Remove enableJdbcCaseSensitivity

### ISSUE THREAD

**Issue by pgruetter** [smart-data-lake/smart-data-lake#221]
**Is your feature request related to a problem? Please describe.**
As discussed in #219 we can probably get rid of the environment variable enableJdbcCaseSensitivity. 

**Describe the solution you'd like**
Remove Enviornment.enableJdbcCaseSensitivity and any functions that use it.

**Further requirements**
We should follow common conventions in relational databases when it comes to case sensitivity. In Oracle, table names are case insensitive unless you quote them: `"Schema"."Name"` is case sensitive, `schema.name` is not. In MSSQL backticks are used. 

In SDL/Hocon config quotes can be added to values as follows:
```
""Name""
`Name`
"`Name`"
```
The first " only tells HOCON that the value should be interpreted as a string and is removed by the Hocon parser.
If a db or table name starts with quotes, SDL needs to handle these names case sensitive. 
Note that in SQL the quoted names can also contain other special characters like slashes, dots or hyphens.

**Comment by pgruetter** [comment]
Analyzed the requirements as stated above and I have to revise that:
MSSQL uses brackets [schema].[table] not backticks, backticks are used in MySQL i.e.

We should really leave it up to the JDBC driver to handle case sensitivity. So for this issue:
- Remove Environment.enableJdbcCaseSensitivity as originally stated
- Make sure that escape sequences in Hocon are passed on correctly, i.e. for SQL Server:
```
table {
   db = "["dbo"]" 
   name = "["nameWithSpecialCharacters"]"
}
```
or for case sensitive table names in Oracle:
```
table {
   db = "\""schema"\""
   name = "\""caseSensitiveTableName"\""
}
```

**Comment by zzeekk** [comment]
> ```
> table {
>    db = "["dbo"]" 
>    name = "["nameWithSpecialCharacters"]"
> }
> ```
I agree, thats much better. But why do you use "["nameWithSpecialCharacters"]" and not "[nameWithSpecialCharacters]" for mssql? I guess the second " is absorbed by Hocon as well, but then it's not needed at all, right?
