### ISSUE TITLE
Maven: 'artifactId' contains an expression but should be a constant

### ISSUE THREAD

**Issue by kaelte** [smart-data-lake/smart-data-lake#26]
https://github.com/smart-data-lake/smart-data-lake/blob/71dcc36fe5c0d8e3fbcd8b9367ed3d6ab2837cf0/pom.xml#L25

Maven complains:

> [WARNING] Some problems were encountered while building the effective model for io.smartdatalake:smartdatalake_2.11:jar:1.0.0-SNAPSHOT
[WARNING] 'artifactId' contains an expression but should be a constant. @ io.smartdatalake:smartdatalake_${scala.minor.version}:1.0.0-SNAPSHOT, /Users/klaus/GIT/smart-data-lake/pom.xml, line 25, column 14
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.

**Comment by zzeekk** [comment]
Hi @kaelte , see discussion in #24. I dont know a solution to do cross compiling with maven pom without this warning. There would be nice solution with sbt, but we use maven for now.
