### ISSUE TITLE
Support multiple outputs for CustomFileAction

### ISSUE THREAD

**Issue by zzeekk** [smart-data-lake/smart-data-lake#29]
It is a common use case of file transformation to split a big input file into multiple output files. To support this CustomFileAction should support multiple outputs (currently it is one input to one output)

Ag the same time CustomFileAction could be refactored to work with Input/OutputStream and not only FSDataInput/OutputStream. This is currently only a type restriction, but the underlying implementation should support all subclasses of java Input/OutputStream's.

An additional small improvement would be to add a configuration attribute to force execution on the driver (current implementation is that the transformation is executed distributed on the executors).

**Comment by pgruetter** [comment]
@zzeekk Will close this as won't do as it was never actually requested or needed.
