### ISSUE TITLE
DataObject without CanHandlePartitions gets replaced by dummy DataFrame in exec

### ISSUE THREAD

**Issue by MarkusRothSBB** [smart-data-lake/smart-data-lake#321]
**Describe the bug**
If you implement a DataObject that does not extend the trait CanHandlePartitions, it gets replaced by a dummy DataFrage during the exec phase, which leads to no data being written by any action to the target DataObject.

**To Reproduce**
Create a DataObject that does not have the trait CanHandlePartitions. Write to it using a CopyAction from a DataObject that does have partitions defined (e.g. CsvFileDataObject). Note that no data is written to the target DataObject.

**Expected behavior**
Data should be written to the target DataObject.

**Additional context**
The call stack where the replacement with a dummy DataFrame happens is: SparkSubFeedAction.exec -> doTransform -> validateAndUpdateSubfeed -> subFeed.clearPartitionValues -> breakLineage. The pattern matchin SparkAction.validateAndUpdateSubfeed is the culprit - it should probably have an additional case that clears partitions, but does not break lineage.

**Comment by MarkusRothSBB** [comment]
The issue seems to be fixed with https://github.com/smart-data-lake/smart-data-lake/pull/320/commits/16eb529ca624876379c740fd6853399dd8457b89

**Comment by zzeekk** [comment]
Fixed with commit 60d3f5ca55966d5ee763d34ed7ae2dd44f424748
