### ISSUE TITLE
Recovery re-executes actions skipped with no-data

### ISSUE THREAD

**Issue by zzeekk** [smart-data-lake/smart-data-lake#349]
**Describe the bug**
Recovery of a failed run re-executos actions skipped because they had no data. This should not happen as they have been skipped by intention and doesn't need to be re-executed. 

There is another problem with multiple attempts: the state file for an attempt only includes runtime information of the current attempt. If there are multiple attempts runtime information from older attempts get lost and actions are re-executed.

**Expected behavior**
Recovery should ignore actions skipped because they have no data.
Recovery should write full runtime information, including information from previous attempts.

**Comment by pgruetter** [comment]
Included in Release 1.2.5 and 2.0.4.
