### ISSUE TITLE
Implement KafkaDataObject / Streaming Execution Mode

### ISSUE THREAD

**Issue by zzeekk** [smart-data-lake/smart-data-lake#35]
Planned Features:
- Structure Streaming triggerOnce
- Partition over time and defined ChronoUnit
- Schemaregistry integration to decode key and value type

**Comment by swissrussdev** [comment]
As a thought: I think it might be sensible to extend the file objects to support the FileStream DataStreamReader first. This uses pretty much identical mechanisms as the Kafka source and is much easier to write unit tests for as you don't need a broker. That way we can get the architecture implications cleanly implemented before adding Kafka, which tbh is the easy bit.

**Comment by zzeekk** [comment]
Hi @swissrussdev , ok for me. We would first read / write a file stream then. That would means to extend the SparkFileDataObject for streaming.
Did you already try EmbeddedKafkaCluster for unit tests?

**Comment by swissrussdev** [comment]
Great - will try to get  look at this. Regarding  tests, thanks for the tip : what about https://index.scala-lang.org/manub/scalatest-embedded-kafka/scalatest-embedded-kafka-streams/2.0.0?target=_2.12? Looks pretty straightforward and well maintained.

**Comment by zzeekk** [comment]
Hi @swissrussdev , just went through the existing code and have the following suggestions:

1. Rename CanWriteDataStream -> CanWriteStreamingDataFrame, because we might support other streaming engines in the future. DataFrame still indicates that it's related to Spark DataFrame.

2. Remove partitionValues parameter from CanWriteDataStream.writeDataStream, as we cannot filter a streaming DataObject with partition values this will be always empty. You can pass partitionValues=Seq() later in foreachBatch / writeDataFrame.

3. We should separate execution logic from DataObjects. I suggest to change the following things:
  a) KafkaTopicDataObject.isStream: a DataObject configuration should not fix the way it can be accessed in the configuration. I therefore suggest to create an additional interface CanReadStreamingDataFrame, where an Action can get the StreamingDataFrame for this DataObject, and remove the configuration attributes isStream.
  b) In ParquetFileDataObject (SparkFileDataObject) and JdbcTableDataObject, the new configuration attributes streamingOptions and trigger are also about execution logic. They are only needed if you want to write this DataObject in streaming mode. I suggest to create a new ExecutionMode SparkStreamingMode which includes streamingOptions and trigger configuration (see existing PartitionDiffMode as an example). For now we implemented initExecutionMode in the different Actions which can be used to control the data to be processed on the start nodes of the DAG. For SparkStreaming we need new configuration attribute "executionMode" on every Action, which defines the execution mode for this Action regardless of its position in the DAG. Finally we have to pass an additional parameter streamingMode: SparkStreamingMode to CanWriteStreamingDataFrame.writeDataFrame, in order to have streamingMode and trigger available.

4) We should think about extracting most important options from streamingOptions into a separate attribute, e.g. checkpointLocation. Like that it's documented in ScalaDoc.

5) We should give the streaming query a name for better traceability in Spark UI, e.g. df.writeStream.queryName("query1")... In my opinion the name should be something like "<Action> writing <DataObject>". I suggest to pass the name as additional parameter in CanWriteStreamingDataFrame.writeDataFrame.

For my part of the batch KafkaDataObject i didn't get yet confirmation of my other customer to include it in SDL. I will check next week.

Let me know if/where you want to help me on the points above.

**Comment by swissrussdev** [comment]
Hi @zzeekk, 
Thanks for your thoughts and sorry for the delay. Most of this I agree with totally and had worked out as I learned more about the core last week! The trait was actually originally CanWriteStreamingDataFrame - I only changed it on discovering that structured streaming implements the function over a DataStreamWriter and wanted to stay close to this naming. Your input makes sense though. Queryname and special treatment for trigger/checkpoint (perhaps also watermark) options are also a no-brainer.

100% with you on moving streaming to an execution mode/actions. I would also consider generally implementing the write via foreachbatch and writeDataFrame. That way every DataObject can be a target for streaming sources without additional logic - and can be implemented in SparkSubFeedAction for all standard actions (Copy, Historize etc.). In multiple output scenarios this does throw up some issues for recoverability and exactly-once writing, but I think we can delegate this to the implementation - the requirements of these actions are so specific anyway that I think we should grant full freedom on requirements relating to how this is handled. 

I'll try to implement this in my spare time over the next week and then let you have a look at what damage I've caused, ok?

**Comment by zzeekk** [comment]
Great, let me know if there is something to review.

**Comment by swissrussdev** [comment]
Actually, doing it the way I suggest, we don't need the CanWriteStreamingDataFrame trait at all.  Use the execution mode to initiate the DataStreamReader on a DO with CanCreateStreamingDataFrame, then wrap writeDataFrame in the StreamingQuery logic from the execution  mode. That way we can both support all output DO types.

**Comment by swissrussdev** [comment]
Thoughts for execution modes:
1) I'd make 2: one with Trigger.Once() and optionally one with Trigger.ProcessingTime(t). They have such different implications and config is likely to be messy to generalise. Alternative, need to create a configurable TriggerConfig trait which wraps the Trigger. Instances.
2) We need to cover mulriple input/output cases, where the inputs can be a mix of streaming and batch. Typically unions are all streaming and joins are a mix. I would suggest that the execution mode should accept an optional list of input DOs which should be initiated in batch mode. For the simple case this is of course None, so single feed actions don't require this.

**Comment by zzeekk** [comment]
> Actually, doing it the way I suggest, we don't need the CanWriteStreamingDataFrame trait at all. Use the execution mode to initiate the DataStreamReader on a DO with CanCreateStreamingDataFrame, then wrap writeDataFrame in the StreamingQuery logic from the execution mode. That way we can both support all output DO types.

I could imagine it would be easier to use optimized streaming sinks (Kafka) with a dedicated CanWriteStreamingDataFrame, but ok for me to keep it simple for the beginning.

**Comment by zzeekk** [comment]
> Thoughts for execution modes...

1) makes sense for me to have TriggerOnceMode and ProcessingTimeMode (which keeps running...). I would focus on TriggerOnceMode for now. For ProcessingTimeMode we are no longer in Batch mode when starting SmartDataLakeBuilder. We will need different startup behaviour...
I guess you also include checkpointLocation in the ExecutionMode configuration.

2) Yes, good sugestion

**Comment by zzeekk** [comment]
@swissrussdev: I added my stuff to this issues branch: kafka batch read with partition listing and schema registry type conversion. Please merge with potential local commits of you.

**Comment by zzeekk** [comment]
We also need to think about the possible transitions between different excecution modes in the DAG and what the desired behaviour should be:
- Spark default (PartitionValues) | PartitionDiffMode -> SparkStreamingOnce
  - get a new StreamingDataFrame
  - partitionValues are cleared
- SparkStreamingOnce -> Spark default (PartitionValues)
  - get a new normal DataFrame
  - The following Action can only read the whole table
- SparkStreamingOnce -> PartitionDiffMode
  - get a new normal DataFrame
But we also need to take care to pass the schema along in init-phase, because tables/files might not exist yet (see also #119). We could create an empty DataFrame with the schema and pass it along to solve this.

**Comment by swissrussdev** [comment]
Bit confused by this as I thought the execution mode primarily impacted init nodes - which would mean that changes in execution mode only become relevant if you break lineage, and in that case the dataframe is reinitialised according to the settings of the data object/action.
Otherwise the main input/output implicitly propagate the dataframe through the DAG according to their initexecutionmode. Have I completely misunderstood this?

**Comment by zzeekk** [comment]
Hi @swissrussdev, but dont you have the use case to have multiple SparkStreamingOnce-Actions in a chain? In my opinion that's not very far. You may also first have a FileTransfer-Action and then a SparkStreamingOnce-Action. Or probably very often a SparkStreamingOnce-Action and then a normal SparkBatch-Action.
Currently there is the property initExecutionMode which is taken as ExecutionMode if this is one of the start Actions in the DAG. Then there is a new property executionMode which is applied also if this Action is not a start Action. Applying SparkStreamingOnceMode only if it's a start Action of the DAG doesn't make sense. In my opinion a SparkStreamingOnce-Action should always run as such, and not only if it's a start Action. Therefore executionMode property should be used.

**Comment by swissrussdev** [comment]
Ok, missed that change, makes sense. I agree with your proposed transitions. We'll need to find a clean way of extending this as number of execution modes grows (Delta?)

**Comment by zzeekk** [comment]
First Unit-Test with pipeline of two SparkStreamingMode-Actions is working :-)
