### ISSUE TITLE
Databricks 8.X compatibility

### ISSUE THREAD

**Issue by pgruetter** [smart-data-lake/smart-data-lake#355]
**Is your feature request related to a problem? Please describe.**
Reach compatibility with Databricks Runtime 8.X

**Describe the solution you'd like**
SDL Version 2.0.4 does not run on Databricks Runtime 8.0 because of incompatible libraries. 
We use json4s-core version 3.6.6, Databricks updated this to a milestone (!) release 3.7.0-M5 starting with Databricks Runtime 8.0.
Json4s is used in ActionDAGRunState.scala.

**Additional context**
It's possible that more libraries will follow after json4s and this was just the first one that popped up.

**Comment by pgruetter** [comment]
In json4s 3.7.0-M5, Formats was split into separate classes which is why ShortTypeHints is not found anymore.
Further changes are necessary though.

**Comment by zzeekk** [comment]
@pgruetter: An alternative solution would be to get rid of json4s. I used it because kxbmap-configs was not yet able to write data. With the new version used for "fail on superfluous keys" it's also possible to write Hocon or Json. The code for writing the state files could be migrated to kxbmap-configs then...

**Comment by pgruetter** [comment]
@zzeekk Good point, we should get rid of json4s now. I read into kxbmap and did a first try in branch https://github.com/smart-data-lake/smart-data-lake/tree/replace-json4s-with-kxbmap. I'm currently stuck on a few ConfigWriters and Readers so I just added some dummies so it compiles.

For example, I don't understand why ConfigWriter[RuntimeInfo] needs anything special, it's a case class that uses types that should all be defined (out-of-the-box or in ActionDAGRunState now like LocalDateTime). I used a dummy to just output toString but of course this can't be parsed back by the ConfigReader.

**Comment by pgruetter** [comment]
The version from https://github.com/smart-data-lake/smart-data-lake/commit/587b79863946dd140322736a151394d6f68ab7d4 works correctly. 

It does introduce a breaking change regarding durations:
In the past, we used java's toString: https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html#toString--
Kxbmap transforms these values according to Hocon: https://github.com/lightbend/config/blob/master/HOCON.md#duration-format

When migrating to the latest SDL version, one needs to manually update the durations in the latest state file from
`PT5.35S` to `535ms`.
Not sure if we should overwrite ConfigWriter and -Reader to be backward compatible.

**Comment by zzeekk** [comment]
@pgruetter: PT5.35S is ISO standard format. I suggest to create a custom writer.

**Comment by pgruetter** [comment]
@zzeekk I did have a try, but it always took the definition from kxbmap instead of my own. Will try again tomorrow, yes.

**Comment by zzeekk** [comment]
@pgruetter: made a commit to read/write Duration in ISO format. Can you check?

**Comment by pgruetter** [comment]
@zzeekk Yes, it works correctly. Somehow, I forgot to include the durationWriter when I tried it, rest was identical. 
Anyway, with that, we're fully backward compatible 👍 
Also made a diff between old and new state files: bit hard because the order is completely different, but all data types seem to be identical. 

I'll create a pull request.

**Comment by pgruetter** [comment]
Closed by #361
