### ISSUE TITLE
How to skip subsequent actions if no data was processed

### ISSUE THREAD

**Issue by pgruetter** [smart-data-lake/smart-data-lake#363]
For FileIncrementalMoveMode, an action is skipped if there is no data and subsequent actions are also skipped by default.
Is it correct, that this functionality doesn't work with other actions, i.e. CopyAction or CustomSparkAction?

For example: I have a JMSDataObject that may or may not read any data. It is visible in the metrics written when the action is done. If there was no data fetched, I don't want to execute any subsequent actions.

**Comment by zzeekk** [comment]
@pgruetter: It's actually the ExecutionMode that can throw a NoDataToProcessDontStopWarning to skip the current action. Following actions are then skipped depending on executionCondition (default is to skip if at least one input subfeed was skipped).
Currently PartitionDiffMode, SparkIncrementalMode and FileIncrementalMoveMode check if new data is available. There is also CustomPartitionMode which could check for now data. Unfortunately they dont work for JMSDataObject as it is not partitioned and increments are already given by the source...
We would need a general CustomExecutionMode which can take custom code to check on JMSDataObject for new data. Or an additional trait CanCheckForNewData which has function "hasNewData(): Boolean" for sources like JMS or Kafka which are incremental on their own...
How important is that for your project?

**Comment by pgruetter** [comment]
@zzeekk Thanks a lot for the explanation. For the current project, it's not important at all! The action should actually always have data when it's executed. If it doesn't, the subsequent actions still run correctly, they just don't have anything to process.
So in this instance, it's more an optimization question.
