### ISSUE TITLE
Schema evolution fails with NoSuchElementException: None.get

### ISSUE THREAD

**Issue by pgruetter** [smart-data-lake/smart-data-lake#369]
**Describe the bug**
If there's a schema evolution and columns can not be converted automatically, an exception `Caused by: java.util.NoSuchElementException: None.get` is thrown.

**To Reproduce**
Force a schema evolution from decimal(38,10) to decimal(3,0). 

**Expected behavior**
Problem is here: https://github.com/smart-data-lake/smart-data-lake/blob/0a6dda684d387d5001cf0a688af20dd2aff368b2/sdl-core/src/main/scala/io/smartdatalake/util/evolution/SchemaEvolution.scala#L205

If convertedColumns.isEmpty, the resulting error messages tries to call convertedColumns.get which of course will always fail.
I assume the message should read `column $c cannot be converted from ${o.simpleString} to ${n.simpleString}.

**Comment by MarkusRothSBB** [comment]
I stumbled over this during the integration of Snowflake (see: https://github.com/smart-data-lake/smart-data-lake/issues/339). I fixed it locally, but never added the fix. I think your correction is the right one.

**Comment by pgruetter** [comment]
@MarkusRothSBB Thanks a lot for your feedback. I didn't even see that this particular line was changed in https://github.com/smart-data-lake/smart-data-lake/commit/3c4fee58421162f6c2cdb140fa7f680f8230c6aa, so the referenced line doesn't make too much sense ;-) I was still on version 1.2.1 which is why I didn't see the fix when analyzing the problem. 

It looks like you changed it to the exact message that I'm proposing here. I'm closing this issue, but I agree that #339 should be fixed to allow lower precision fields.
