### ISSUE TITLE
DeltaLake: <table> is not a Delta table

### ISSUE THREAD

**Issue by pgruetter** [smart-data-lake/smart-data-lake#375]
**Describe the bug**
When executing an action that writes into a Delta Lake table on Windows, the feed fails with the following error
```Exception in thread "main" io.smartdatalake.workflow.TaskFailedException: Task int-5g failed. Root cause is 'AnalysisException: `data/int/int-5g-antennas` is not a Delta table.' ```

**To Reproduce**
The issue can be reproduced with the following application.conf:
```
dataObjects {
  opendata-swiss-5g-antennas {
    type = WebserviceFileDataObject
    url = "https://data.geo.admin.ch/ch.bakom.mobil-antennenstandorte-5g/data/ch.bakom.mobil-antennenstandorte-5g_en.json"
  }

  stg-5g-antennas {
    type = JsonFileDataObject
    path = "data/stg/5g-antennas.json"
    schema = "`crs` STRUCT<`properties`: STRUCT<`name`: STRING>, `type`: STRING>,`features` ARRAY<STRUCT<`geometry`: STRUCT<`coordinates`: ARRAY<BIGINT>, `type`: STRING>, `properties`: STRUCT<`description`: STRING, `id`: BIGINT, `lang`: STRING, `powercode_en`: STRING>, `type`: STRING>>,`name` STRING,`type` STRING"
  }

  int-5g-antennas {
    type = DeltaLakeTableDataObject
    path = "data/int/~{id}"
    table {
      db = default
      name = "int_antennas"
      primary-key = [id]
    }
  }
}

actions {
  stg-5g {
    type = FileTransferAction
    inputId = opendata-swiss-5g-antennas
    outputId = stg-5g-antennas
    metadata {
      feed = 5g-stg
    }
  }

  int-5g {
    type = HistorizeAction
    inputId = stg-5g-antennas
    outputId = int-5g-antennas
    transformer.sqlCode = "select features.properties.id, features.geometry, features.properties.powercode_en from (select explode(features) as features from stg_5g_antennas)"
    metadata {
      feed = 5g-int
    }
  }

}
```

**Expected behavior**
When executing the above 2 feeds, it is expected that a DeltaLake table is created.

**Additional context**
Tried a similar pipeline on Linux and didn't run into theses problems.

**Comment by pgruetter** [comment]
It's not a Windows problem per se, the following code works correctly (not using SDLB):

```
def main(args: Array[String]): Unit = {
  val spark = SparkSession
    .builder()
    .appName("Delta Test")
    .config("spark.master","local")
    .getOrCreate()

  val data = spark.range(0,100)
  data.write.format("delta").save("delta-table")
}
```

**Comment by pgruetter** [comment]
Problem seems to be in getDataFrame of DeltaLakeTableDataObject:
While session.read works for normal parquet tables if it doesn't exist, it doesn't work for Delta Tables. 

@zzeekk : We can check in getDataFrame if a table exists and if it is a Delta Table. What should we return if the table does not exist? Returning an empty DataFrame (with empty schema) won't work, i.e. HistorizeAction expects to find dl_ts_captured, dl_ts_delimited.

**Comment by zzeekk** [comment]
@pgruetter: Problem is that isTableExisting is not implemented properly (always true). But we should also update DeltaLakeTableDataObject using the DeltaLake table API. I will prepare a branch for you...

**Comment by zzeekk** [comment]
@pgruetter: Should work with branch https://github.com/smart-data-lake/smart-data-lake/compare/feature/375-update-delta-lake, please check

**Comment by hiltpold** [comment]
@zzeekk https://github.com/smart-data-lake/smart-data-lake/compare/feature/375-update-delta-lake does not compile, there seems to be a type mismatch in GlobalConfig.scala:94.
