### ISSUE TITLE
Support collecting custom metrics

### ISSUE THREAD

**Issue by zzeekk** [smart-data-lake/smart-data-lake#377]
**Is your feature request related to a problem? Please describe.**
Observe custom metrics for executed Spark queries, e.g. Number of Records with special flag, Number of new version in HistorizeAction...

**Describe the solution you'd like**
Spark 3 has a new interface called "observable metrics": https://jaceklaskowski.github.io/mastering-spark-sql-book/new-and-noteworthy/observable-metrics.
Add a configuration option to CopyAction to define observable metrics and add them in Log entries with Statistics writing to DataObject.

**Comment by pgruetter** [comment]
Could be linked to #450

**Comment by zzeekk** [comment]
With this mechanism we should also collect metric numRecords for KafkaTopicDataObject and JdbcTableDataObject.
