### ISSUE TITLE
DAG Build fails if first action is SparkSubFeedsAction

### ISSUE THREAD

**Issue by swissrussdev** [smart-data-lake/smart-data-lake#38]
If multiple data objects serve as the subfeeds for the first action in an ActionDAGRun, the application fails with the message: "Loop detected in remaining nodes". The issue can be reproduced as follows:
1) Run the feed custom-rating-csv from sdlexamples to initialise the two csv data objects
2) Change the feed name in the metadata for action customRatingAgg to "spark-subfeeds-action" and run the new feed

Part of the issue appears to be in DAG.sortStep, since in the calculation of remainingNodeIdsWithoutIncomingStartNodes the .diff only eliminates one instance of each node from the remainingNodes list, whereas an initial SparkSubFeedsAction references 2 init nodes.

**Comment by zzeekk** [comment]
Hi @swissrussdev, looks like a real bug :-)
i was able to reproduce it and created a unit test for it which fails with
`assertion failed: Loop detected in remaining nodes a
java.lang.AssertionError: assertion failed: Loop detected in remaining nodes a`
I pushed my unit test to branch bugfix/38-first-action-multiple-inputs, glad if you can fix the bug (on the same branch).
