### ISSUE TITLE
Data Quality built into pipelines

### ISSUE THREAD

**Issue by pgruetter** [smart-data-lake/smart-data-lake#388]
**Is your feature request related to a problem? Please describe.**
With custom transformers you already have the power to implement any logic in your feeds. So it's already possible to build in some quality rules and / or checks. 
However, I think this can be simplified and offered as a standard functionality of SDL.

**Describe the solution you'd like**
Especially with the new transformer API (#344) we could hook a generic "quality transformer" into any pipelines. 

I'm thinking about two features at the moment:
* Define expressions to check thresholds for warnings and / or errors. If a warning expression evaluates to true, write warnings to the logfile. If an error expression evaluates to true, fail this feed. (is there a better way than displaying warnings in the Log?)
* Define logic to write "bad data" to another data object for further analysis. If data meets the criteria in this expression, it is not written to the output DataObject but rather to a special Data Object where it can be further analyzed. 

**Additional context**
Number of warnings / failures should probably also be visible in the metrics.
Maybe there's additional logic / features that should be implemented in this transformer. Up for discussion.

**Comment by Geheiner** [comment]
The results of the checks could be displayed by the Rest-Info API (and later be pushed by websockets) once this is implemented : https://github.com/smart-data-lake/smart-data-lake/issues/450

**Comment by zzeekk** [comment]
"Define expressions to check thresholds" could be implemented using #377 for Spark. From a performance perspective this would be optimal.

**Comment by zzeekk** [comment]
Is probably also linked with #43

**Comment by pgruetter** [comment]
@zzeekk @Geheiner  Should we kick this can down the road, or do constraints and expectations (see https://smartdatalake.ch/docs/reference/dataQuality) actually cover everything we need for the moment?

**Comment by Geheiner** [comment]
write "bad data" to another data object for further analysis is probably not covered currently right ? I'm not sure how urgently we need this though as I have to say I never used the feature in a real scenario for now

**Comment by zzeekk** [comment]
We have a DataValidationTransformer to validate records and create an errorsColumn, but i think its not yet used widely. A subsequent CustomDfsTransformer could route this to an error SubFeed.
In my opinion we can close the issue for now, and reopen later if we have new concrete project requirements.
