### ISSUE TITLE
Implement lineage visualization in Javascript

### ISSUE THREAD

**Issue by zzeekk** [smart-data-lake/smart-data-lake#39]
Implement customized lineage visualization prototype with D3. 
Features:
- Highlight dependencies and impact when selecting a data object
- Draw a box around data objects of the same layer
- Optimize layout
- Visualize additional informations

**Comment by zzeekk** [comment]
I created a prototyp in sdl-examples branch https://github.com/smart-data-lake/sdl-examples/tree/feature/39-lineage-visualization

See Readme section to give it a try: https://github.com/smart-data-lake/sdl-examples/tree/feature/39-lineage-visualization#lineage-visualization

**Comment by pgruetter** [comment]
@zzeekk OK if we close this one here?
