### ISSUE TITLE
WebserviceFileDataObject generates bad filenames when specifying partitionLayout

### ISSUE THREAD

**Issue by Geheiner** [smart-data-lake/smart-data-lake#394]
**Describe the bug**
When using WebserviceFileDataObject with option partitionLayout, the resulting filenames start with a dot ".".
These are then not readable by the following Actions.

**To Reproduce**

        dataObjects {
          ext-departures {
            type = WebserviceFileDataObject
            url = "https://opensky-network.org/api/flights/departure"
            partitionLayout = "?airport=%airport%&begin=1630200800&end=1630310979"
            partitionDefs = [{name = "airport", values = ["LSZB", "EDDF"]}]
            readTimeoutMs=200000
          }
          stg-departures {
            type = JsonFileDataObject
            path = stg-departures
            partitions = ["airport"]
        
          }
        }
      actions {
        download-departures {
          type = FileTransferAction
          inputId = ext-departures
          outputId = stg-departures
          metadata {
            feed = download
          }
        }
      }
This results in files named
.airport-EDDF.begin-1630200800.end-1630310979.json

which cannot be read properly by subsequent actions

**Expected behavior**
Filenames should not start with "."
**Additional context**

**Comment by Geheiner** [comment]
I think I have the fix, just need to be able to build SDL locally...

**Comment by pgruetter** [comment]
@Geheiner Thanks for that! I added you to "Comitters", so you should be able to created branches now.

**Comment by Geheiner** [comment]
Wow thanks for the reactivity on a saturday evening!!! :)
