### ISSUE TITLE
Upgrade to Spark 3.2

### ISSUE THREAD

**Issue by zzeekk** [smart-data-lake/smart-data-lake#406]
**Is your feature request related to a problem? Please describe.**
Spark 3.2 is out - it has many updated dependencies which might be important for projects (avro 1.10, hadoop 3.3)

**Describe the solution you'd like**
Update Spark dependency and dependencyManagement in sdl-parent pom to spark version 3.2

**Comment by pgruetter** [comment]
We need to discuss if and how we can handle different spark versions. In Databricks i.e. the latest LTS version only supports 3.1.2 and is supported until Sep 23, 2023. If we only support Spark 3.2, we force everyone to move to a newer Databricks runtime version which are usually only supported for 6 months.
