### ISSUE TITLE
Optionally deduplicate input data in DeduplicationAction

### ISSUE THREAD

**Issue by zzeekk** [smart-data-lake/smart-data-lake#428]
**Is your feature request related to a problem? Please describe.**
Currently DeduplicationAction assumes that input data is unique over the primary key of the output DataObject. Often this is true, but sometimes not. It can be made unique by a transformer, but this involves repeating the definition of primary key in the transformer code.

**Describe the solution you'd like**
Implement a additional configuration attribute deduplicateInputData: Boolean = false. When set to true apply df.dropDuplicates to input DataFrame.

**Comment by zzeekk** [comment]
Alternatively this could be implemented as Transformer, but it would need the primary key of the output data object. This could be achieved by adding the current action to the ActionPipelineContext. Should we create a separate ticket for that?

**Comment by zzeekk** [comment]
It would be better to configure rank cols/expressions in order to control which duplicate records are discarded...

**Comment by pgruetter** [comment]
@ThierryGirod I think this one will actually be solved by #806, correct?

**Comment by ThierryGirod** [comment]
@pgruetter no because I created a DeduplicateTransformer not updated the action.

**Comment by zzeekk** [comment]
In my opinion this issue is solved by DeduplicateTransformer, as it now supports to get the primary key of the Actions output DataObject, e.g.:

```
  deduplicate-departures {
    type = DeduplicateAction
    inputId = stg-departures
    outputId = int-departures
    mergeModeEnable=true
    transformers = [{
      type = DeduplicateTransformer
      rankingExpression = "lastSeen desc"
    }]
  }
```

I improved documentation of DeduplicateTransfomer and DeduplicateAction accordingly.
