### ISSUE TITLE
Advanced Validation

### ISSUE THREAD

**Issue by pgruetter** [smart-data-lake/smart-data-lake#43]
It should be possible to define more validations, i.e. column restrictions (domains, limits, not null), foreign key constraints.
They should be validated & reported by smart data lake builder.

Interesting Spark Library "Deequ": https://github.com/awslabs/deequ

**Comment by zzeekk** [comment]
Interesting product: https://owl-analytics.com/

**Comment by zzeekk** [comment]
It's now possible to define Constraints on DataObjects that are validated for each row when writing. See also http://smartdatalake.ch/docs/reference/dataQuality#constraints

**Comment by pgruetter** [comment]
I'll close this PR as the requirements should be fulfilled by constraints and expectations.
