### ISSUE TITLE
Implement Delta Execution Mode

### ISSUE THREAD

**Issue by pgruetter** [smart-data-lake/smart-data-lake#44]
ActionPipelines should allow delta mechanisms (only load new data). This would also greatly help recovery procedures.

**Comment by swissrussdev** [comment]
Hi @pgruetter,
I reckon the work @zzeekk and I have started on structured streaming integration  could make this fairly straightforward. It would require a few custom microbatch readers to define "what is new data", but the underlying checkpointing mechanism is precisely for that purpose.

**Comment by zzeekk** [comment]
Hi @swissrussdev , you're right, structured streaming execution mode with triggerOnce works well for all SparkFileDataObjects. We can also write to all the other DataObjects (Hive, Jdbc, ...). But we cannot read delta's from Hive or Jdbc, as there is no source for them (https://spark.apache.org/docs/latest/structured-streaming-programming-guide.html#input-sources).
We therefore plan for another execution mode which checks compares a "comparable" column in source and target DataObject for the delta, which then serves as parameter for spark batch.

**Comment by swissrussdev** [comment]
Hi @zzeekk, I know there aren't existing DataSources for Jdbc/Hive, but it appears to be a case of implementing MicrobatchReader. Given that you get the whole checkpointing infrastructure for free, isn't that an alternative worth considering?

**Comment by swissrussdev** [comment]
Following up on this : a big bonus with the structured streaming approach is that it works even when the target is heavily transformed - in particular if the reference column is aggregated (e.g. timestamp to date) or denormalized.

**Comment by swissrussdev** [comment]
This is the sort of thing I mean.

https://github.com/sutugin/spark-streaming-jdbc-source

 Hive would be pretty much identical. Splunk/Web are trickier - but the direct comparison with target columns is if anything more difficult to implement.

**Comment by zzeekk** [comment]
Nice example. I like the approach. It has at-least-once guaranteed, but not exactly-once, isn't it?

**Comment by swissrussdev** [comment]
True - but I think that's an issue which we'll have anyway if we want to support arbitrary sinks using foreachbatch, multiple targets etc. Transactional targets e.g. JDBC/TickTock will be ok - needs a health warning for writing to non-tx targets, but we can support a LOT of use cases this way.

**Comment by zzeekk** [comment]
Name to be discussed: SparkIncrementalMode or SparkDeltaMode? With SparkDeltaMode we have some conflicts with DeltaLake, e.g. DeltaLakeTableDataObject.

**Comment by swissrussdev** [comment]
I'll open a new issue for extending the SparkStreamingOnce mode with non-standard sources so this issue can be closed when you're done.
