### ISSUE TITLE
Implement Language server to provide code completion for configuration

### ISSUE THREAD

**Issue by zzeekk** [smart-data-lake/smart-data-lake#440]
**Is your feature request related to a problem? Please describe.**
To find which properties an Action or DataObject supports, i find myself often checking scaladoc and code. It would be nice to have code completion for configuration files available in different IDE's like IntelliJ or VSCode.

**Describe the solution you'd like**
Code completion can be provided to IDE's by a language server implementation, see https://microsoft.github.io/language-server-protocol. A language server for SDL Hocon Files should be created. 
A first step in this direction has already been made: SDL's configuration schema is defined as json schema, see also http://smartdatalake.ch/JsonSchemaViewer.

In these issue a language server should be implemented, that takes SDL's configuration schema as input, and can suggest valid entries for a specific cursor position in a given configuration file. In order to lookup the valid configuration entries for a specific cursor position, the language server needs to parse Hocon Files keeping the position/origin of the parsed tokens. Interestlingly the standard Hocon Parser already supports this to a certain amount, but there seems to be a bug with endLineNumber.
- Tokenizer.tokenize returns an Iterator<Token>, each Token contains it's origin
- Parsable.rawParseDocument tokenizes an input and creates a SimpleConfigDocument.
- SimpleConfigDocument has ConfigNodeRoot configNodeTree, including all parsed tokens with their origin - but endLineNumber is not properly set
- ConfigParser then creates a SimpleConfig, including the origin for all entries - but endLineNumber is not properly set

A first step would therefore be to improve Hocon Parser to set endLineNumber correctly, and add start/endColumn or start/endPosition.

**Comment by zzeekk** [comment]
Interesting Ressources:

Sample language server using LSP4J framework:
https://medium.com/ballerina-techblog/implementing-a-language-server-how-hard-can-it-be-part-1-introduction-c915d2437076
https://github.com/ballerina-platform/ballerina-lang/blob/master/language-server/modules/langserver-core
https://github.com/ballerina-platform/lsp4intellij

Intellij Hocon Plugin:
https://github.com/AVSystem/intellij-hocon

ANTLR
Hocon Grammar:
https://github.com/jdevelop/go-hocon/blob/master/parser/HOCON.g4
Code Completion:
https://github.com/mike-lischke/antlr4-c3
https://neuroning.com/post/implementing-code-completion-for-vscode-with-antlr/
Incremental Parsing:
https://github.com/dberlin/antlr4ts/blob/incremental/IncrementalParsing.md

**Comment by pgruetter** [comment]
@zzeekk @dsalathe I propose to close this issue for now. We have our MVP of the LSP. Further enhancements should be proposed / discussed in the separate repo.
