### ISSUE TITLE
Data Loads

### ISSUE THREAD

**Issue by pgruetter** [smart-data-lake/smart-data-lake#45]
Scheduling, Monitoring
Vision: DAG is calculated, the ActionPipeline is automatically built with all steps to satisfy user query. I.e: Load Reporting Layer for Data X: The ActionPipeline automatically builds and checks for data in all lower layers (stage, integration, btl..). Report early, if data is missing and job will not be able to complete.

**Comment by zzeekk** [comment]
@pgruetter: What is missing here? i suggest to close this.

**Comment by pgruetter** [comment]
Totally agree, I'll close it.
