### ISSUE TITLE
Implement VolatileSparkDataObject

### ISSUE THREAD

**Issue by pgruetter** [smart-data-lake/smart-data-lake#46]
For some more complex data flows an intermediate DataObjects which will not be persisted could be of interest. It can be used to chain Actions without storing the intermediate result.

Implement a new VolatileSparkDataObject, which CanRead/WriteDataFrame (implement traits). It stores the DataFrame it gets from writeDataFrame, and output it on getDataFrame.

If getDataFrame is called before writeDataFrame an exception must be thrown.

**Comment by zzeekk** [comment]
New transformer API makes it possible to chain transformtions, which solves this problem. This issue is obsolete now.
