### ISSUE TITLE
Maven profile for Spark 3.1

### ISSUE THREAD

**Issue by MarkusRothSBB** [smart-data-lake/smart-data-lake#465]
**Is your feature request related to a problem? Please describe.**
Snowpark is not yet compatible with Spark 3.2. For this reason, the Snowpark transformations in sdp-snowflake are currently broken. (The immediate problem is that [Snowpark relies on Jackson 2.10.0](https://search.maven.org/artifact/com.snowflake/snowpark/1.1.0/jar) as it is in Spark 3.1, but Spark 3.2 upgraded to Jackson 2.12.3.)

**Describe the solution you'd like**
A Maven profile for selecting Spark version, so that Spark 3.1 can be selected to fix sdp-snowflake.

This issue is not high priority right now, as it can be expected that Snowflake will soon release a new version of Snowpark that supports Spark 3.2. Still, the same situation might arise in the future with Snowpark or other dependencies.

**Comment by zzeekk** [comment]
Implemented profile 'fat-jar-for-spark-3.1' - it creates a fat-jar without spark like profile 'fat-jar', but adapts some version properties to include the correct library of spark-extension, delta-lake and json4s, in order to run with a Spark 3.1 distribution.

**Comment by MarkusRothSBB** [comment]
Nice! Thanks a lot for this! We will test this in the next couple of days.
