### ISSUE TITLE
Dangling links to scaladocs

### ISSUE THREAD

**Issue by mand35** [smart-data-lake/smart-data-lake#466]
**Describe the bug**
In the documentation are multiple times still links to non existing scaladocs pages. These need to be replaced with links to the proper pages of the *Configuration Schema Viewer*

**To Reproduce**
One example is the `API Docs` link on the Select column page in part one (just before the `try it out` section). 

**Expected behavior**
working links

**Comment by pgruetter** [comment]
Solved by #467
