### ISSUE TITLE
Create a Scala Transformer providing Dataset API

### ISSUE THREAD

**Issue by zzeekk** [smart-data-lake/smart-data-lake#489]
**Is your feature request related to a problem? Please describe.**
Create a ScalaClassSparkDsTransformer, which allows to define a transformation by using Spark Dataset API.
Using Spark Dataset API allows using case classes to define and validate the schema required by the transformation.

**Describe the solution you'd like**
ScalaClassSparkDsTransformer allows to implements a one-to-one transformation in Scala with Spark Dataset API. An additional configuration parameter caseClass must be provided to define the schema of the input dataset. At runtime SDLB will receive a DataFrame an try to convert it to a corresponding Dataset.
The transformation can create an arbitrary Dataset as output, which is converted back to a DataFrame by SDLB.

**Additional context**
In the future we could also create a many-to-many transformation using Spark Dataset API, but i suggest to validate the approach in 1:1 transformation first.

**Comment by Geheiner** [comment]
So, the next step is to support a generic number of inputs/outputs.
I think the best way to implement this is analoguous to how Scala Itself implemented Tuples:
We create Transformers for all possible numbers of input/output datasets. The number of classes that would be needed is the maximum number of inputs times the maximum number of outputs. I suggest to start by supporting a maximum number of 5 for now.
This would require to create 25 transformer classes (24 in addition to the one that was already created).
Here is the list of all possible combinations of transformers that would need to be built:
```
1:1

2:2
2:1
1:2

3:3,
3:2,3:1,
1:3,2:3

4:4
4:1,4:2,4:3,
1:4,2:4,3:4

5:5
5:1,5:2,5:3,5:4,
1:5,2:5,3:5,4:5

num combinations with 1 = 1
num combinations with 2 = 4
num combinations with 3 = 9
num combinations with 4 = 16 
num combinations with 5 = 25
```

**Comment by Geheiner** [comment]
Now there exists a generic N to 1 transformer for Datasets, some improvements have been added in this PR: https://github.com/smart-data-lake/smart-data-lake/pull/545
The feature has been tested in a real setting and it works, the ticket can be closed
