### ISSUE TITLE
The FromConfigFactory object defined by ParseableFromConfig implementations is being ignored

### ISSUE THREAD

**Issue by pgruetter** [smart-data-lake/smart-data-lake#49]
Currently, the ConfigParser looks for the companion object of each SdlConfigObject and checks whether it implements a method called "fromConfig" that has the expected signature.

It does not respect what is returned by the "factory" method.

If the companion object does not implement the fromConfig method, or if this method does not follow the expected signature exactly, then an error occurs when the ConfigParser parses the config.

Currently, all DataObjects and Actions follow the expected convention but the contract implied by the interfaces does not enforce this.

A better solution is that the config parsing respects the definition of the factory method.

UPDATE:

Probably the best approach would be to let all DO/Action implementations implement ParsableFromConfig directly which almost forces them to declare the companion object as a factory. Furthermore, a macro/annotation can be created that generates the necessary implementation at compile time which should make the definition of new DOs and Actions straight forward.

**Comment by pgruetter** [comment]
@zzeekk Is this still open?

**Comment by zzeekk** [comment]
It's still not the nicest implementation, but we dont have a problem here. If ok for you, please close it.
