### ISSUE TITLE
Define DataObject Schema by Scala CaseClass

### ISSUE THREAD

**Issue by zzeekk** [smart-data-lake/smart-data-lake#512]
**Is your feature request related to a problem? Please describe.**
For several DataObjects a schema can be specified. Currently this has to be done as Spark DDL. This is ok if you have no Java project, otherwise it would be nice to define the schema by a case class, as done for Spark Datasets.

**Describe the solution you'd like**
Allow to specify a case class name as schema instead of Spark DDL string. Use prefix "caseClass#" to differentiate from DDL string.

**Comment by zzeekk** [comment]
And json schema or xml schema would also be nice...

**Comment by zzeekk** [comment]
Implemented schema providers for caseClass, jsonSchemaFile and xsdFile.

The configuration format is as follows: `<schemaProviderId>#<schemaProviderConfiguration>`.
Examples:
- "ddl#a int, b string"
- "caseClass#com.test.TestSchema"
- "xsdFile#/user/abc/test.xsd;testRowTag" - note that xsdFile normally needs an additional row tag option to define the subelement of the xsd to get the schema for. See also [[SchemaProviderType]]
- "jsonSchemaFile#/user/abc/testSchema.json;testRowTag" - note that also jsonSchemaFile normally needs an additional row tag option to define the subelement...
- "a int, b string" - this uses default schema provider "ddl", which makes this change backward compatible.

**Comment by zzeekk** [comment]
Schema providers for caseClass, jsonSchemaFile, xsdFile and avroSchemaFile implemented.

Open points:
- RowTag for schema must be given as XPath expression (e.g. separated by slashes), but RowTag of SparkDataSource is just a tag. If the tag is present in different places of the schema, every occurance is read by SparkDataSource - this might create confusion if schemas of different places is not the same... i think these should be fixed in SparkDataSource, or needs preprocessing of XML.
- Read XSD schemas with recursive definitions - this needs a configuration to limit the recursion depth.

**Comment by mand35** [comment]
Just have it stated here: we also need support for recognizing arrays in XML files (XSD schema)
So far the schema parser does interpret the following as struct, not array:
```
  <xs:element name="tariffNodes" minOccurs="0">
        <xs:complexType>
          <xs:sequence maxOccurs="unbounded">
```
