### ISSUE TITLE
Schema Viewer shows wrong information

### ISSUE THREAD

**Issue by zzeekk** [smart-data-lake/smart-data-lake#518]
**Describe the bug**

1. Type of WebserviceFileDataObject.partitionsDefs is strange:
http://smartdatalake.ch/json-schema-viewer/index.html#viewer-page?v=2-23-11
WebservicePartitionDefinition is actually a case class and its attribute should be rendered.

2. Definition (text for this element) is wrong, e.g. from another element?!
http://smartdatalake.ch/json-schema-viewer/index.html#viewer-page?v=2-23-1

3. Definition text should be converted to HTML to render special characters and new lines.

4. Translation section (beyond definition text) can be removed as we dont provide translations.

**Comment by zzeekk** [comment]
Point 3 & 4 are solved. But 1 and 2 remains, see WebserviceFileDataObject.

**Comment by Geheiner** [comment]
Additional example:
In the JSON Schema Viewe, the text displayed for the persist Option of a CustomDataframeAction is the one belonging to the breakDataFrameLineage Option:
![image](https://user-images.githubusercontent.com/6410125/174611302-a0a07f14-6d80-48a1-a4a0-f728c60f133f.png)
