### ISSUE TITLE
Docu: version update

### ISSUE THREAD

**Issue by mand35** [smart-data-lake/smart-data-lake#530]
After [updating the getting-started version](https://github.com/smart-data-lake/getting-started/issues/7#issue-1240141531) the getting-started guide need to be changed: 
* [x] no **additional** / **separate** `download` is necessary before running the `compute` feed. Thus, both feeds can be run in one go, without separation.
* The Actions need to be renamed:
   -  [x] join-departure-airport is now a `CustomDataFrameAction` 
   - [x] compute-distances utilizes a transformer of type `ScalaClassSparkDfTransformer`
   - [x] download-deduplicate-departures (part3) now utilizes `ScalaCodeSparkDfTransformer`
* [x] fix on [compute-distances](https://smartdatalake.ch/docs/getting-started/part-1/compute-distances) the .* in the commands need tp be `".*"`
* [x] on page [data-lake-format](https://smartdatalake.ch/docs/getting-started/part-2/delta-lake-format) set `unzip part2.additional-files.zip` as real command
* [x] typo `podmanrun` on [customWebservice](https://smartdatalake.ch/docs/getting-started/part-3/custom-webservice)
* [x] part 3 has changes in the custom action sources
* [x] in [part3](https://smartdatalake.ch/docs/getting-started/part-3/incremental-mode) need `--hostname=localhost` to be added to the SDLB command

**Comment by pgruetter** [comment]
@mand35 Since all tasks are closed on this one, can we close this issue or is there something left to do?

**Comment by mand35** [comment]
@pgruetter strange, in the history it is mentioned as closed already. But yes, we can close.
