### ISSUE TITLE
JsonSchemaViewer broken

### ISSUE THREAD

**Issue by mand35** [smart-data-lake/smart-data-lake#536]
**Describe the bug**
The JsonSchemaViewer is hanging during load up. 
Maybe since the version dropdown update.

**To Reproduce**
open https://smartdatalake.ch/JsonSchemaViewer/

**Expected behavior**
the viewer loads up and presents the data

**Comment by mand35** [comment]
Using the local docusaurus version with the latest version of the documentation, the Schema viewer including the dropdown works as expected.

**Comment by zzeekk** [comment]
It failed on github pages because you cannot list directory with a http request to get a list of the schemas available.
I created and index.json file with a schema list. The index.json file is created during docusaurus build by a custom plugin implementing the postBuild hook.
