### ISSUE TITLE
Activate Merge Mode on existing tables

### ISSUE THREAD

**Issue by pgruetter** [smart-data-lake/smart-data-lake#539]
**Is your feature request related to a problem? Please describe.**
When using merge mode on a historization action, a column dl_hash is added to your DataObject which is used to detect changes. 
This works fine when merge mode is activated for a new DataObject (that has never been written before). 
When activating it for a DataObject with existing data, schema evolution takes care to add the column dl_hash, but it's empty for all existing records. 

**Describe the solution you'd like**
First, check if the current solution works. It's likely, that all previous records (with empty dl_hash) get closed and a new record with dl_hash is created. If that's the case, we can discuss to leave it like that.
The cleaner solution would be to calculate dl_hash for all previous records on activation.

**Comment by pgruetter** [comment]
@ThierryGirod Is it possible that this issue is also fixed by #807 ?

**Comment by ThierryGirod** [comment]
@pgruetter in the test case I implemented the existing data had also a no hash value set. So no not solved.
