### ISSUE TITLE
Support for Apache Iceberg

### ISSUE THREAD

**Issue by pgruetter** [smart-data-lake/smart-data-lake#541]
**Is your feature request related to a problem? Please describe.**
We should add support for Apache Iceberg.

**Describe the solution you'd like**
A `sdl-iceberg` module with a Data Object for Apache Iceberg.
Iceberg is similar to Delta Lake in many regards (partitioning, time-travel..), so functionality from a SDL perspective should be similar.

**Additional context**
Iceberg supports different file formats (Parquet, ORC, AVRO), it makes sense to support all.
Iceberg also supports true schema evolution (drop column, rename column) so it needs to be analyzed how we would handle it.

**Comment by zzeekk** [comment]
This would be also very interesting regarding snowflake integration:
https://www.snowflake.com/blog/iceberg-tables-powering-open-standards-with-snowflake-innovations/?lang=de
