### ISSUE TITLE
Update to Spark 3.3

### ISSUE THREAD

**Issue by zzeekk** [smart-data-lake/smart-data-lake#549]
**Is your feature request related to a problem? Please describe.**
Spark 3.3 is released. We should update SDLB to use the latest Spark Version by default.
An Interesting change in Spark 3.3 is the use of log4j 2.x instead of 1.x, which is deprecated a long time ago.

**Describe the solution you'd like**
Tasks:
- [x] create new branch develop-spark3.3 in spark-extensions and release
- [x] update smart-data-lake (dependency versions in parent pom.xml!)
- [ ] update getting-started
- [x] update delta-lake library

**Comment by pgruetter** [comment]
@zzeekk : this is on the list for Release 2.5.0. Are there any open points here, or can we close it?

**Comment by pgruetter** [comment]
Updating getting-started moved to #668 .
