### ISSUE TITLE
mvn versions:set fails

### ISSUE THREAD

**Issue by pgruetter** [smart-data-lake/smart-data-lake#56]
Hi @zzeekk 
The release pipeline failed because maven gets a NPE executing
`mvn versions:set -DnewVersion=1.0.0`

Found similar cases, but in our case it's because we have an expression in the artifactId:
`smartdatalake_${scala.minor.version}`

As a quickfix we could hard code the minor version 2.11 again, then the build process should continue. But we need to find a solution for this.

**Comment by zzeekk** [comment]
Hi @pgruetter , we could replace the first occurence of the old version with the new one like this:
`sed -i '/1.0.0-SNAPSHOT/{s//1.0.0/;:p;n;bp}' pom.xml`
Maybe we could additionally add <version>...</version> to the pattern to replace...

**Comment by pgruetter** [comment]
I was hoping to go without directly manipulating the file, as we might run into more trouble with other maven plugins down the road. 
But agreed, let's go like this for the moment.

Note that the ' have to be replaced by " because I'm using variables for the version numbers.

**Comment by swissrussdev** [comment]
Classifiers? http://maven.apache.org/guides/mini/guide-building-for-different-environments.html

**Comment by pgruetter** [comment]
> Classifiers? 

Also stumbled upon a question on that specific question (scala version in artifactId) and they discuss Classifiers:
https://stackoverflow.com/questions/35022831/dynamic-maven-artifactid
Not sure if it will work for us (see discussion about transitive dependencies).

**Comment by pgruetter** [comment]
Checked the stackoverflow discussion. If I understand correctly, this uses the replacer plugin to replace the expressions for the target folder, so the warning would still be displayed. 

Since the sed command is working alright for our build pipeline, I propose to abandon this issue. 
@zzeekk @swissrussdev What do you think?

**Comment by zzeekk** [comment]
Ok for me.

**Comment by swissrussdev** [comment]
Good for me as well.
