### ISSUE TITLE
SDL uses vulnerable version 1.2.17 of log4j

### ISSUE THREAD

**Issue by kaelte** [smart-data-lake/smart-data-lake#573]
Smart DataLake uses the version 1.2.17 of log4j:
https://github.com/smart-data-lake/smart-data-lake/blob/9cd8656a7a8eccd8dd17a94148f3a076a8a564a7/pom.xml#L290
1.2.17 has been classified as vulnerable, see also
https://ossindex.sonatype.org/component/pkg:maven/log4j/log4j@1.2.17

**Comment by zzeekk** [comment]
This will be fixed by #549
