### ISSUE TITLE
Export resolved configuration as json file

### ISSUE THREAD

**Issue by zzeekk** [smart-data-lake/smart-data-lake#575]
**Is your feature request related to a problem? Please describe.**
SDL Visualizer is slow parsing hocon configurations with many objects.

**Describe the solution you'd like**
Create a command line tool to export the parsed and resolved Hocon configuration as json file

**Additional context**
As the standard Hocon parser supports getting the origin of a configuration entry, it would be nice to add this as additional property for first class configuration objects, e.g. connections, actions, dataObjects. It should be possible to disable this functionality.

**Comment by Geheiner** [comment]
Nice timing as I'm currently working again on https://github.com/smart-data-lake/smart-data-lake/issues/481.
I could use this code to send the HOCON Config as JSON to the RemoteAgent

**Comment by zzeekk** [comment]
New CommandLine Tool io.smartdatalake.meta.configexporter.ConfigJsonExporter.scala in module sdl-lang implemented.
