### ISSUE TITLE
Warn if given columns in transformation don't exist

### ISSUE THREAD

**Issue by pgruetter** [smart-data-lake/smart-data-lake#577]
**Is your feature request related to a problem? Please describe.**
When you define a BlacklistTransformer, it is not clear if the given columnBlacklist is applied to the source DataObject (which could still be CamelCase), the internal presentation (Spark) or the output DataObject. 
It's the internal one, so it needs to be in lowercase as CamelCase column names get converted. As user, you don't get a warning or error, the BlacklistTransformer simply doesn't do anything

**Describe the solution you'd like**
Print a warning if the given columns do not exist. 
Could apply to other transformers.

**Comment by ddeuber** [comment]
The only other transformer which has the same problem is the WhitelistTransformer.
