### ISSUE TITLE
Can't use same ExcelFileDataObject for write and read

### ISSUE THREAD

**Issue by pgruetter** [smart-data-lake/smart-data-lake#580]
**Describe the bug**
See the example below. Reading an Excel from a WebserviceFileDataObject creates a file called result.xlsx in the specified path. 
When reading this same ExcelFileDataObject with a second action, the following error is thrown:

> Exception in thread "main" io.smartdatalake.util.dag.TaskFailedException: Task int-bfs-commune-register failed. Root cause is 'FileNotFoundException: C:\<path-to>\bfs-commune-register (Access is denied)'
> Caused by: java.io.FileNotFoundException: C:\<path-to>bfs-commune-register (Access is denied)
> 	at java.base/java.io.FileInputStream.open0(Native Method)
> 	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
> 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
> 	at org.apache.hadoop.fs.RawLocalFileSystem$LocalFSFileInputStream.<init>(RawLocalFileSystem.java:146)
> 	at org.apache.hadoop.fs.RawLocalFileSystem.open(RawLocalFileSystem.java:275)
> 	at org.apache.hadoop.fs.ChecksumFileSystem$ChecksumFSInputChecker.<init>(ChecksumFileSystem.java:161)
> 	at org.apache.hadoop.fs.ChecksumFileSystem.open(ChecksumFileSystem.java:372)
> 	at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:976)
> 	at com.crealytics.spark.excel.WorkbookReader$.readFromHadoop$1(WorkbookReader.scala:60)

If you manually change the path (only for reading the file in int_*) to "bfs-commune-register/result.xlsx", the exception changes to:

> Exception in thread "main" io.smartdatalake.util.dag.TaskFailedException: Task int-bfs-commune-register failed. Root cause is 'IllegalStateException: (stg-bfs-commune-register) No FileSourceScanExec found in execution plan to check if there is data to process'
> Caused by: java.lang.IllegalStateException: (stg-bfs-commune-register) No FileSourceScanExec found in execution plan to check if there is data to process
> 	at io.smartdatalake.workflow.dataobject.SparkFileDataObject$.$anonfun$getFilesProcessedFromSparkPlan$2(SparkFileDataObject.scala:425)
> 	at scala.Option.getOrElse(Option.scala:189)
> 	at io.smartdatalake.workflow.dataobject.SparkFileDataObject$.getFilesProcessedFromSparkPlan(SparkFileDataObject.scala:425)
> 	at io.smartdatalake.workflow.dataobject.SparkFileDataObject.getSparkDataFrame(SparkFileDataObject.scala:215)
> 	at io.smartdatalake.workflow.dataobject.SparkFileDataObject.getSparkDataFrame$(SparkFileDataObject.scala:161)
> 	at io.smartdatalake.workflow.dataobject.ExcelFileDataObject.getSparkDataFrame(ExcelFileDataObject.scala:67)

**To Reproduce**
```dataObjects {
  ext-bfs-commune-register {
    type = WebserviceFileDataObject
    url = "https://dam-api.bfs.admin.ch/hub/api/dam/assets/22484825/master"
  }

  stg-bfs-commune-register {
    type = ExcelFileDataObject
    excelOptions {
      sheetName = GDE
      useHeader = true
    }
    saveMode = Overwrite
    path = bfs-commune-register
  }

  int-bfs-commune-register {
    path = "bfs-commune-register"
    table {
      name = int_bfs_commune_register
      primaryKey = [gdenr]
    }
  }

}

actions {
  stg-bfs-commune-register {
    type = FileTransferAction
    inputId = ext-bfs-commune-register
    outputId = stg-bfs-commune-register
    metadata.feed = stg-bfs-commune-register
  }

  int-bfs-commune-register {
    type = HistorizeAction
    inputId = stg-bfs-commune-register
    outputId = int-bfs-commune-register
    metadata.feed = int-bfs-commune-register
  }

}
```

**Expected behavior**
A ExcelFileDataObject can be used to write and read an Excel file without modification.

**Comment by zzeekk** [comment]
First problem is that spark-excel needs a file an not a path. We should implement listing existing xlsx files in a directory, calling spark-excel for each and union the DataFrames. 

There is a similar issue with spark-xml not supporting partitions. There we implemented listing directories on our own, overriding getDataFrame method from SparkFileDataObject. The problem with overriding getDataFrame method is that there were already new features added to the method in SparkFileDataObject, which have not been added in XmlFileDataObject.

So if possible we should define extension points in SparkFileDataObject that are called by its getDataFrame method, and Excel/XmlFileDataObject just implements this extension points methods.

**Comment by zzeekk** [comment]
There is an additional issue with RelaxedCsvFileDataObject overwriting getSparkDataFrame Method, and missing the block to setup observer.
