### ISSUE TITLE
Schema Viewer does not consistently show Scala class in type

### ISSUE THREAD

**Issue by ddeuber** [smart-data-lake/smart-data-lake#599]
For some elements in the schema the class name (which is encoded as the title in the JSON schema) is not shown.

For an example without the class name see WebserviceFileDataObject.proxy:

![image](https://user-images.githubusercontent.com/10706639/206691313-cc7f3e7a-8b9b-44c0-beda-dfd5671f0caf.png)

An example with the class is WebserviceFileDataObject.metadata:

![image](https://user-images.githubusercontent.com/10706639/206692217-3bb234b4-2a4e-401c-afc2-ea146fb528e4.png)

The class resp. title should be shown consistently on all objects.

**Comment by zzeekk** [comment]
Another similar Problem: Booleans are shown as String, e.g.: PartitionDiffMode.applyPartitionValuesTransform is actionally a Boolean in Scala, but a Strin in the Schema and the Viewer:
![image](https://user-images.githubusercontent.com/13715754/210183275-b35b466e-3ba1-4fcc-a66d-384687e22127.png)
