### ISSUE TITLE
Handle writing no data to DataObject more intelligently

### ISSUE THREAD

**Issue by zzeekk** [smart-data-lake/smart-data-lake#608]
**Is your feature request related to a problem? Please describe.**
Currently when writing to a DataObject it might collect metrics saying that there was no data to process. This is logged, but not used to inform subsequent actions. 

**Describe the solution you'd like**
Inform subsequent actions that input is empty by setting a corresponding attribute on the SubFeed, maybe isSkipped, or something similar.

**Comment by iliassoto** [comment]
I think the solution should separate two cases: 
1. There is no data to process in the first place (the input data object is empty)--> Action should be skipped in my opinion. Currently, reading from an empty ParquetFile causes problems.
2. There is no data to be written in the output DataObject --> Action should be carried out but it attaches a flag isSkipped.

**Comment by zzeekk** [comment]
Also Expectations dont get an answer from the Spark Observation if there is no data... the Error message is confusing.

**Comment by zzeekk** [comment]
We can check if there is Data before writing to DataFrame to the Spark DataSource by adding a custom operation to the Spark plan. Like that we can check if there are any records when executing the Spark plan.

For 1:1 Actions the behaviour then is simple: if there is no data, a NoDataToProcessWarning is thrown, the action is marked as skipped. Nothing is written to the output DataObject.

For 1:n Actions (or also n:m...) it is more complicated. I suggest that a NoDataToProcessWarning is only thrown, if the mainOutput has no data, but not when writing to further outputs. And i also suggest that if the mainOutput has no data, further outputs are processed nevertheless, meaning a mainOutput without data does not stop processing further outputs of the Action. This means the action might be marked as skipped, but has written data to non-main Outputs.
