### ISSUE TITLE
GettingStarted Documentation uses old API and wrong Placeholder id

### ISSUE THREAD

**Issue by dnLeiting** [smart-data-lake/smart-data-lake#648]
There are two bugs in the SDLB - Getting Started documentation.
1. The Placeholder is described as *{~id}* in the description
2. The outdated smartdatalake API getDataFrame() is used in the documentation

The wrong descriptions can be found under following links:
1. https://smartdatalake.ch/docs/getting-started/part-1/get-departures
2. https://smartdatalake.ch/docs/getting-started/part-2/historical-data

The following changes should be adapted:
1. Placeholder id should have the following format in the text *~{id}*
2. The DeltaLakeTableDataObject function getSparkDataFrame() should be used instead of the old function getDataFrame()

**Comment by pgruetter** [comment]
@dnLeiting : This one was solved with #650, correct?

**Comment by dnLeiting** [comment]
Yes.
