### ISSUE TITLE
Reading schema files from classpath location

### ISSUE THREAD

**Issue by zzeekk** [smart-data-lake/smart-data-lake#652]
**Is your feature request related to a problem? Please describe.**
It would be nice to version schema files with the code, and load them from the classpath as resource.
Currently the URI given the reference schema files is strictly treated as Hadoop URI.
On the otherside configuration files can already be loaded from classpath, see also ConfigLoader:95.

**Describe the solution you'd like**
Create a new method that generalizes reading files from URI's. If there is a "cp:" prefix the file will be loaded from classpath.
Replace usage of HdfsUtil.readHadoopFile with the new method (where appropriate).

**Comment by pgruetter** [comment]
Done in #669
