### ISSUE TITLE
Modernize Schema Viewer

### ISSUE THREAD

**Issue by ddeuber** [smart-data-lake/smart-data-lake#656]
The SDL schema viewer suffers from multiple issues:

- It uses obsolete Javascript libraries (e.g. jQuery mobile, tv4).
- The build chain has too many manual steps.
- There are performance issues (see e.g. #644).

Therefore, the schema viewer should be rewritten as a React component. We should also analyze whether the d3 tree structure is still the best way to visualize the schema.

**Comment by ddeuber** [comment]
The definitions section of the SDLB JSON schema is, because of the nested class hierarchy, not conformant with the JSON schema specification: https://datatracker.ietf.org/doc/html/draft-handrews-json-schema-validation-01#section-9:~:text=This%20keyword%27s%20value%20MUST%20be%20an%20object.%20%20Each%20member%20value%20of%20this%0A%20%20%20object%20MUST%20be%20a%20valid%20JSON%20Schema.

We should be consistent with the JSON schema specification because it helps when using JSON schema types in Typescript for the schema viewer. In addition, there might be validation issues when people use the schema for other purposes (e.g. in IDEs).

**Comment by zzeekk** [comment]
Hi @ddeuber, you mean because there are nested definitions?
I validated the schema in different tools, e.g. https://json-schema.hyperjump.io/ and also IntelliJ (JSON Schema Version 7). It seems valid. Do you have a validator that mentions errors?

**Comment by ddeuber** [comment]
Yes, because of the nesting. I noticed it because it is not consistent with the Typescript type JSONSchema7 in @types/json-schema. Apparently, not all schema validators are so strict with the JSON schema. Nevertheless, I think we should follow the specification to be on the safe side.

**Comment by zzeekk** [comment]
I see, you would like to use @types/json-schema. But the latest version of json-schema spec is 2020-12. And they have nested $ref even in their documentation: https://json-schema.org/draft/2020-12/json-schema-core.html#name-dereferencing.
They list other javascript libraries supporting 2020-12 under https://json-schema.org/implementations#validator-javascript.
Do you think it is possible to adapt sdl-schema and what would be the effort for it?

**Comment by ddeuber** [comment]
In 2020-12, the definitions resp. $defs can also not be nested: https://json-schema.org/draft/2020-12/json-schema-core.html#name-schema-re-use-with-defs:~:text=Each%20member%20value%20of%20this%20object%20MUST%20be%20a%20valid%20JSON%20Schema.

But since as this does not seem to be a problem for most schema validators, we will not fix it as a part of this issue. It is also not critical for the schema viewer, even when  using @types/json-schema, it only needs a bit more type casting.
