### ISSUE TITLE
Update to Spark 3.4

### ISSUE THREAD

**Issue by dnLeiting** [smart-data-lake/smart-data-lake#659]
**Is your feature request related to a problem? Please describe.**
Since Spark 3.4 is released a updated of the SDLB to the new Spark Version is from benefit. 
The new Spark version 3.4 includes among others the following interesting features:
- Implement PyTorch Distributor 
- Implement support for DEFAULT values for columns in tables
- Support TIMESTAMP WITHOUT TIMEZONE data type

**Describe the solution you'd like**
The following tasks are included in this feature:
- [x] create new branch develop-spark3.4 in spark-extensions and release
- [x] update smart-data-lake (dependency versions in parent pom.xml!)
- [x] update getting-started
- [x] update delta-lake library

**Comment by pgruetter** [comment]
As discussed, we will not update getting-started until the 2.6.0 release is finalized (otherwise we need to point getting-started to a SNAPSHOT version).
