### ISSUE TITLE
State file: add startTstmp and duration for Init and Prepare phases

### ISSUE THREAD

**Issue by zzeekk** [smart-data-lake/smart-data-lake#671]
**Is your feature request related to a problem? Please describe.**
State files for now only include informations about the execution phase, but not prepare and init phase.
In the Visualizer UI we would like to include prepare and init-phase in the timeline view.

**Describe the solution you'd like**
Add start- and end-time for prepare and init-phase to RuntimeInfo (per Action).
Currently there are startTstmp + duration for exec-phase in RuntimeInfo.
I suggest to add startTstmpPrepare + durationPrepare and startTstmpInit + durationInit attributes.

As we begin to change the state file, we should also add a version number. I suggest to put the sdlbVersion (BuildVersionInfo.readBuildVersionInfo) and the appVersion (AppUtil.getManifestVersion) in ActionDAGRunState.

**Comment by zzeekk** [comment]
@pgruetter : please review suggestion.

**Comment by pgruetter** [comment]
Thanks, looks good! 
Should we also include the addition of a version number to the state file? Can also create a separate issue for that.

**Comment by zzeekk** [comment]
Right, lets add version with this issue as well, i already extended the description.
