### ISSUE TITLE
StackoverflowError when generting json Schema

### ISSUE THREAD

**Issue by iliassoto** [smart-data-lake/smart-data-lake#698]
Sometimes, the deployment phase throws a StackOverflowError error when attempting to execute the step **generate-json-schema**. This execution is defined in the **pom.xml** of the **sdl-lang** package, and it triggers the class **io.smartdatalake.meta.jsonschema.JsonSchemaExporter**. 

**To Reproduce**
Build and deploy the pom.xml file of the sdl-lang package. The error does not always occurr. See for example [Snapshot Build #677](https://github.com/smart-data-lake/smart-data-lake/actions/runs/5288117960) (first attempt)

**Comment by zzeekk** [comment]
Added more logging in the build to find understand this error better the next time it happens:
https://github.com/smart-data-lake/smart-data-lake/commit/f1229a7da8b32e519c40a8dd6e0a4ce03cd6e32a

**Comment by zzeekk** [comment]
This will be solved with #741, https://github.com/smart-data-lake/smart-data-lake/commit/7a7619ebb9b791f77de63ec26099f3ad1ea5981a
