### ISSUE TITLE
Uplad final state to API

### ISSUE THREAD

**Issue by zzeekk** [smart-data-lake/smart-data-lake#700]
**Is your feature request related to a problem? Please describe.**
The final state of a SDLB run should be uploaded to an API for showing it in the UI.

**Describe the solution you'd like**
Extend existing FinalStateWriter with an option to configure an http endpoint, where it uploads the state.

**Comment by zzeekk** [comment]
I finally found it better to create a separate State Listener. It can be configured as follows:
```
global {
  stateListeners = [{
    className = "io.smartdatalake.util.misc.FinalStateUploader"
    options {
      uploadUrl = "https://<api-hostname>/api/v1/run"
      #uploadStagePath = "upload-stage-path"
    }
  }]
}
```
uploadStagePath is optional, if set failed uploads are temporarily stored in this folder and the upload retried on the initialization of the next run.

**Comment by pgruetter** [comment]
Done in #701
