### ISSUE TITLE
Question about failCondition

### ISSUE THREAD

**Issue by AdiWehrli** [smart-data-lake/smart-data-lake#704]
Hello together

We use two `failConditions`, in one action/process. How is this handeled? Must both `failConditions` return `true` to let the action fail or only one? Or wouldn't it fail if the first one would return `false` while the second one would return `true` but the second one will not even be regarded?

Is it even considered to use multiple `failConditions`?

Our `failConditions`:
```json
      // fail conditions
      failConditions = [{
        description = "fail if previous day is not processed after 20:00 on Tuesday-Saturday"
        expression  = "size(selectedOutputPartitionValues) = 0 and coalesce(array_max(transform(outputPartitionValues, x -> x.dt)),'00010101') < date_format(date_sub(runStartTime, 1),'yyyyMMdd') and dayofweek(runStartTime) in (3,4,5,6,7) and hour(runStartTime) >= 20"
      }, {
        description = "fail if partitions are not processed in strictly increasing order"
        expression  = "size(selectedOutputPartitionValues) > 0 and array_min(transform(selectedOutputPartitionValues, x -> x.dt)) < coalesce(array_max(transform(outputPartitionValues, x -> x.dt)),'00010101')"
      }]
```

Thanks very much in advance.

Best regards,
Adi

**Comment by zzeekk** [comment]
Hi @AdiWehrli 

Thanks for the question. According to the configuration schema viewer "Multiple conditions are evaluated individually and every condition may fail the execution mode (or-logic)".

The fail conditions are evaluated in ExecutionMode.scala:88. If one of the conditions evaluates to true an exception is thrown.

Does your example work?

Best, zach

**Comment by AdiWehrli** [comment]
Hello @zzeekk 

Thanks for your answer. 

I analyzed `ExecutionMode` as well and I came to the same conclusion. After a night's sleep and entering this answer I think that the second `failCondition` may be wrong. The problem was as follows:
1. on 08.07. (Saturday) we did **not** received the file for `dt=20230707` but the action was processed successfully (no second `failCondition` occurred)
2. on 09.07. (Sunday) we received the file for `dt=20230708` and the action was processed successfully (no second `failCondition` occurred)
3. on 10.07. (Monday) we received the file for `dt=20230709` **as well as for `dt=20230707`** (delayed) causing the second `failCondition` 

So, that's the point that I do not get. I thought that the action already should fail on 09.07. because the sequence then was `dt=20230706`, `dt=20230708` (no `dt=20230707`).

Thanks in advance for any hint.

Best regards,
Adi

**Comment by AdiWehrli** [comment]
PS: maybe the expression for second `failCondition` should look like this?
```
size(selectedInputPartitionValues) > 0 and array_min(transform(selectedInputPartitionValues, x -> x.dt)) < coalesce(array_max(transform(outputPartitionValues, x -> x.dt)),'00010101')
```
(`selectedInputPartitions` instead of `selectedOutputPartitions`)

**Comment by zzeekk** [comment]
Hi @AdiWehrli ,
in my opinion the second failcondition just checks that the next dt to process is bigger than any already processed dt. This means there can be days without new files but, but if a file arrives late it fails. This is exactly your case. And i also think there might be days that have no files, so the condition is correct.

Now you probably have to decide if you reprocess 07,08,09 by deleting the corresponding partitions in the output, or if it is nevertheless ok to process 07 after 08,09.

Best, zach

**Comment by AdiWehrli** [comment]
Hi @zzeekk 

Yes, we reprocessed the days. So, then let's close this issue. Thanks very much for your help.

Kind regards,
Adi
