### ISSUE TITLE
Implement ScalaClassSparkDfNTo1Transformer

### ISSUE THREAD

**Issue by Geheiner** [smart-data-lake/smart-data-lake#711]
**Is your feature request related to a problem? Please describe.**
DF=DataFrame 
DO=DataObject

When using a CustomDfsTransformer you currently need to provide a Map to tell SDLB which output DF belongs to which DO.
It's best practice to have one Output DO on an Action, so that's the most common case that we encounter.
And when you only have one output DF, the mapping to the DO can be done automatically.

**Describe the solution you'd like**
This is why I propose a new kind of Transformer that does just that:  it takes the same map of dfs to resolve the inputs, but directly accepts a DF as an output.
This will be the signature of transform:
def transform(session: SparkSession, options: Map[String, String], dfs: Map[String, DataFrame]): DataFrame 

This makes the Action writing less error prone.

**Additional context**
Similar efforts were already done with https://github.com/smart-data-lake/smart-data-lake/issues/489 for Datasets.
There we were able to go one step further and also not need the map for the inputs because the DF to DO Mapping could be inferred thanks to the provided case class. For DFs we don't have a case class and just relying on DF/DO Ordering is too risky. That's why I propose to restrict this feature to just automatize the output DF/DO Mapping

**Comment by zzeekk** [comment]
Good idea. I have further suggestions to simplify implementation of a CustomDfsTransformer.
We could provide a default implementation of `CustomDfsTransformer.transform(session: SparkSession, options: Map[String,String], dfs: Map[String,DataFrame]) : Map[String,DataFrame]`, which dynamically searchs for another transform method in the Transformer implementation and dynamically maps paramters.

Example:
The implementation of CustomDfsTransformer could have a method:
`transform(session: SparkSession, dfDataObject1: DataFrame, dfDataObject2: DataFrame, isExec: Boolean, nbOfDts: Option[Int]): DataFrame`
The default implementation of the main CustomDfsTransformer.transform method would map:
- dfs('data-object-1') to dfDataObject1 parameter
- dfs('data-object-2') to dfDataObject2 parameter
- options('isExec').toBoolean to isExec parameter
- options.get('nbOfDts').map(_.toInt) to nbOfDts parameter
- as the function returns only one DataFrame, a Map(outputIds.head, df) can be created as final return value.

The mapping is possible through reflection of parameter types and names. For options we should support primitive types like String, Boolean, Short, Int, Long, Float, Double.

**Comment by zzeekk** [comment]
See https://github.com/smart-data-lake/smart-data-lake/blob/develop-spark3/sdl-core/src/test/scala/io/smartdatalake/workflow/action/spark/transformer/CustomDfsTransformerTest.scala#L41 for an example config & transformer
