### ISSUE TITLE
Spark 3.4.x support

### ISSUE THREAD

**Issue by AdiWehrli** [smart-data-lake/smart-data-lake#714]
**Is your feature request related to a problem? Please describe.**
Is there a roadmap for SDL on behalf of Spark 3.4.x support?

**Describe the solution you'd like**
-

**Additional context**
-

**Comment by pgruetter** [comment]
Hello @AdiWehrli 
We just merged version 2.5.1 yesterday including some issues we still wanted in the Spark 3.3.x branch.
We will soon switch to version 2.6.0 which targets Spark 3.4.x. 

Work on the upgrade has already started on branch https://github.com/smart-data-lake/smart-data-lake/tree/feature/659-update-spark-3.4. 
Feel free to test already and send feedback if something doesn't work.

**Comment by AdiWehrli** [comment]
Thanks very much, @pgruetter.
