### ISSUE TITLE
POM sdl-parent.xml > org.apache.commons:commons-compress must be unique

### ISSUE THREAD

**Issue by AdiWehrli** [smart-data-lake/smart-data-lake#715]
**Describe the bug**
Apparently `org.apache.commons:commons-compress` is non-uniquely specified in sdl-parent POM. The following warning message appears on start of a Maven build:
```
[WARNING] Some problems were encountered while building the effective model for ch.postfinance:oi-tau-export:jar:RE23D-SNAPSHOT
[WARNING] 'dependencyManagement.dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.apache.commons:commons-compress:jar -> version ${commons-compress.version} vs 1.21 @ io.smartdatalake:sdl-parent:2.5.0, C:\Tools\maven-repo\io\smartdat
alake\sdl-parent\2.5.0\sdl-parent-2.5.0.pom, line 2831, column 25
```

**To Reproduce**
Build a project that uses sdl-parent:2.5.0 as parent POM.

**Expected behavior**
No POM warning is shown.

**Additional context**
The dependeny `org.apache.commons:commons-compress` is specified as dependency in `<dependencyManagement>` with its version property, but it also is specified later in `<dependencies>` with the explicit version `1.21`.

**Comment by zzeekk** [comment]
This is fixed with #706

**Comment by AdiWehrli** [comment]
👍🏽

**Comment by AdiWehrli** [comment]
In SDL 2.5.2 the same problem occurs again:
```
1801 [WARNING] 'dependencyManagement.dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.apache.commons:commons-compress:jar -> version ${commons-compress.version} vs 1.21 @ io.smartdatalake:sdl-parent:2.5.2, /builds/oi/tau/tau-export/.m2/repository/io/smartdatalake/sdl-parent/2.5.2/sdl-parent-2.5.2.pom, line 2857, column 25
```

**Comment by zzeekk** [comment]
No problem anymore in current version 2.7.0-SNAPSHOT.
