### ISSUE TITLE
Has the timestamp format changed with 2.5.0?

### ISSUE THREAD

**Issue by AdiWehrli** [smart-data-lake/smart-data-lake#716]
**Describe the bug**
We changed SDL version of one of our projects to 2.5.0. 

One unit test (at least) complains now that the returned value is not equal the expected due to different timestamp formats after calling `GenericRowWithSchema.toString`:
returned timestamp: `2020-10-07 00:00:00.0`
expected timestamp: `2020-10-07 00:00:00`

We see that a one-digit-decimal was appended. This was not the case with SDL 2.4.2.

**To Reproduce**
Steps to reproduce the behavior: this would mean to upload our whole project for performing the concerning unit test.

**Expected behavior**
The timestamp should be as described above.

**Additional context**

**Comment by zzeekk** [comment]
Hi @AdiWehrli, i think this has more to do with the Spark version used, as GenericRowWithSchema is defined in spark-catalyst library. Can you confirm that you upgraded the Spark version as well?
(Default for SDLB 2.4.2 was Spark 3.2.x, where as SDLB 2.5.0 is on Spark 3.3.x.)

**Comment by AdiWehrli** [comment]
Well, we ran already 2.4.2 on Spark 3.3.2. 🤔

**Comment by AdiWehrli** [comment]
Strange. It works on Linux Maven build, but not on local Maven build on Windows.

**Comment by zzeekk** [comment]
Hi @AdiWehrli,
I was thinking about this issue and must state, that we dont do timestamp formatting for data in SDLB.
You rely on the string formatting of objects in your unit tests, which i think is not ideal.
I would recommend to not compare the String representation of a Row in unit tests, but the actual objects of each column.
For instance you could use row.toSeq() to get a Seq[Any], or row.getValuesMap(fieldnames), see also https://spark.apache.org/docs/latest/api/scala/org/apache/spark/sql/Row.html.
With that you're no longer dependent on a the string representation of Row.
WDYT?

**Comment by AdiWehrli** [comment]
Somehow the problem is now solved.
