### ISSUE TITLE
Question: would SDL 2.5.1 work with Spark 3.3.3?

### ISSUE THREAD

**Issue by AdiWehrli** [smart-data-lake/smart-data-lake#723]
Hello together

I was wondering, if SDL 2.5.1 also would run on Spark 3.3.3?

Thanks very much in advance for your answer.

Kind regards,
Adi

**Comment by zzeekk** [comment]
Hi @AdiWehrli,
We just updated the version table, see http://smartdatalake.ch/docs/architecture#sdlb-version-2x
But it answers your questions only half... so here the other half - yes, Spark is compatible between patch versions, means using any 3.3.x version with SDL 2.5.x should work without customizations.
Best, Zach

**Comment by AdiWehrli** [comment]
Thanks for the clarification.
