### ISSUE TITLE
Issue with Polynote installation in Getting Started Guide Part 2

### ISSUE THREAD

**Issue by ThierryGirod** [smart-data-lake/smart-data-lake#731]
**Description:**
The installation process for Polynote, as described in the Getting Started Guide, encounters a problem due to an outdated Spark version URL in the `install_spark.sh` script. This issue results in a 404 error when trying to download Spark from an incorrect URL.

**Reason:**
The issue arises from the attempt to download Spark version 3.3.2 from the following URL, which is no longer available:
[https://dlcdn.apache.org/spark/spark-3.3.2/spark-3.3.2-bin-hadoop3.tgz](https://dlcdn.apache.org/spark/spark-3.3.2/spark-3.3.2-bin-hadoop3.tgz)

**Steps to reproduce:**
To reproduce this issue, follow the Getting Started Guide [Part 2](https://smartdatalake.ch/docs/getting-started/part-2/delta-lake-format) and execute all commands provided until you reach the section titled "Reading Delta Lake Format with Spark." In this section, running the following command:

```bash
docker-compose -f part2/docker-compose.yml build
```
will result in the following error:

```bash
0.316 + wget --progress=dot:giga https://dlcdn.apache.org/spark/spark-3.3.2/spark-3.3.2-bin-hadoop3.tgz
0.375 --2023-09-30 14:58:40--  https://dlcdn.apache.org/spark/spark-3.3.2/spark-3.3.2-bin-hadoop3.tgz
0.389 Resolving dlcdn.apache.org (dlcdn.apache.org)... 151.101.2.132, 2a04:4e42::644
0.397 Connecting to dlcdn.apache.org (dlcdn.apache.org)|151.101.2.132|:443... connected.
0.433 HTTP request sent, awaiting response... 404 Not Found
0.445 2023-09-30 14:58:40 ERROR 404: Not Found.
0.445 
------
failed to solve: process "/bin/sh -c sed -i 's/\\r$//' install_spark.sh && chmod +x install_spark.sh && ./install_spark.sh" did not complete successfully: exit code: 8
```

**Possible fix (worked for me)**
A possible fix for this issue is to update the Spark version in the `part2/polynote/Dockerfile` file. Change the property `ARG SPARK_VERSION` from "3.3.2" to "3.3.3".

**Comment by pgruetter** [comment]
Thanks @ThierryGirod 
There is actually an open PR for that : https://github.com/smart-data-lake/getting-started/pull/17 since I didn't add any reviewers. @mand35 created a more generic way [here](https://github.com/smart-data-lake/getting-started/blob/training_solution/polynote/Dockerfile#L27), will include that.

**Comment by zzeekk** [comment]
This is fixed, getting-started and polynote-lab now uses latest bugfix version for the given Spark minor version.
