### ISSUE TITLE
JDBC Table : Direct Table Writes

### ISSUE THREAD

**Issue by pgruetter** [smart-data-lake/smart-data-lake#747]
**Is your feature request related to a problem? Please describe.**
Currently when writing to a JDBCTableDataObject called `one`, SDL will first write into a temp table called `one_sdltemp` and only after writing all data, execute the merge statement into the final table `one` to have everything written in one transaction.
This is not always desirable, as we can't assume to always have create table rights in the target database.

**Describe the solution you'd like**
Add a flag (on the connection?) to disable these merge statements and write to the final table directly.
Proposal for attribute name:
`directTableWrite`

**Comment by zzeekk** [comment]
implemented `JdbcTableConnection.directTableOverwrite`. If set to true and saveMode=Overwrite, it will overwrite directly the target table, without using a temporary table.
Note that saveMode=Append does not use a temporary table independent of directTableOverwrite.
And saveMode=Merge always needs a temporary table to execute the SQL Merge statement.
