### ISSUE TITLE
Create a Generic Transformer for null handling

### ISSUE THREAD

**Issue by pgruetter** [smart-data-lake/smart-data-lake#755]
**Is your feature request related to a problem? Please describe.**
One common transformation is handling null values in various columns. We could provide a generic transformer to handle these.

**Describe the solution you'd like**
Create a new transformer called `ConvertNullValuesTransformer`.

Parameters: 
`whitelist` (default=None), `blacklist` (default=None), `valueForString` (default="na"), `valueForNumber` (default=-1)

Function:
Replaces all null values in columns of String type with `valueForString` and for number types with `valueForNumber`. 
If `whitelist` is set, only applies it to the given list. If `blacklist` is set, these columns are excluded. If neither is set, applies the function to all columns.

**Additional context**
- I don't think setting a boolean value makes sense. Both true and false as default are dangerous.
- Check if the given columns actually exist in the Data Object to alert the user of any typos.

**Comment by ThierryGirod** [comment]
@pgruetter Please tell me if I understand it right. `whitelist` and `blacklist` are lists with column names? What should happen when both are set and especially a column appears in both? I think this case you forgot to describe.

Last but not least should this class be implemented for both versions -> spark 2 and spark 3

**Comment by pgruetter** [comment]
Yes, both are lists with column names. See the existing `WhitelistTransformer` and `BlacklistTransformer` as example. 
I would add an assert statement to check that only one of the two is set. If both are set, the outcome is unpredictable and doesn't make sense.

And no, we only focus on Spark 3.
