### ISSUE TITLE
Allow dataframes from file sources to optionally include the filename

### ISSUE THREAD

**Issue by swissrussdev** [smart-data-lake/smart-data-lake#76]
Often filenames contain additional metadata regarding the payload (for example snapshot date or region). It would be useful to optionally include this so that it can be parsed using custom logic. A considerable increase in parallelization could also be achieved. 

Implementation using:
https://spark.apache.org/docs/1.6.2/api/java/org/apache/spark/sql/functions.html#input_file_name()

**Comment by zzeekk** [comment]
+1

**Comment by swissrussdev** [comment]
Additional idea: regex pattern parameter to extract the partition name directly from the filename? Would eliminate custom code requirement in most instances.

**Comment by zzeekk** [comment]
We already have something similar for SFtpFileRefDataObject. With partitionLayout you can extract parts of the path as partition columns, and replace them with columns values on writing.
For HadoopFileDataObjects this is not possible on writing, as filename is set by Spark. partitionLayout is set statically in HadoopFileDataObject, but is used only for directories.

So typically filename is parsed on ingestion with FileRefSubFeeds. Files are then written to HadoopFS and partition columns mapped as directories. How are your files ingested to HadoopFS?

To support this we could introduce an additional filenameLayout property on HadoopFileDataObjects, but if it is defined, these DataObjects are read-only for Spark.

**Comment by swissrussdev** [comment]
I'll need to check that - I wasn't proposing anything quite that radical! My proposal was read only - I'll try to get some details posted soon.

**Comment by swissrussdev** [comment]
Had a chance to reread this - 100% agreed. This has to be read only due to HadoopFS naming, but any other source (local FS, plus HDFS files created via HDFS put etc.) can be treated  exactly as you describe. One for 1.0.4.
