### ISSUE TITLE
SnowflakeTableDataObject needs preSql option

### ISSUE THREAD

**Issue by olena-kummer** [smart-data-lake/smart-data-lake#762]
When battling Timestamp Issues between snowflake timestamp conversions and other systems, it is necessary for us to be able to set the timezone in snowflake, before writing the data, so that it will take the correct timezone. For that the preSql statement option, similar in functionality to the one in JdbcTableDataObject, is needed.

Thank you!

**Comment by zzeekk** [comment]
Similar to KafkaTopicDataObject and KafkaConnection, an additional attribute "options: Map[String, String] = Map()" should be added to configure options as listed in https://docs.snowflake.com/en/user-guide/spark-connector-use#additional-options. A "preSql" statement could be configured by using "preactions" option.

KafkaTopicDataObject.options should override KafkaConnection.options for a concrete DataObject.
