### ISSUE TITLE
Collect count metric for Action input.

### ISSUE THREAD

**Issue by zzeekk** [smart-data-lake/smart-data-lake#782]
**Is your feature request related to a problem? Please describe.**
When Actions fail, it is sometimes helpful to know the number of records read from every input DataObject.

**Describe the solution you'd like**
Collect count metric on data read from input DataObject.
Metric name suggestion: "count#\<DataObjectId\>".

**Additional context**
- In Spark this can be done efficiently using Observations.
- For Snowpark there is no such thing. Using a separate count query might produce wrong results and costs performance. I suggest to leave this for now.

**Comment by zzeekk** [comment]
Additionally it would be nice to validate an Expectation on the "transfer rate", e.g. outputCount / mainInputCount.

**Comment by PMuellerELCA** [comment]
Also make it possible to add metrics in pre and postRead. 

When extracting records from a remote system incrementally, it would be useful the get the total count of records in that source table and be able to compare it with the record count in the target. I would implement that in the ODataDataObject as a seperate query in the postRead method.

**Comment by zzeekk** [comment]
Implemented creating "count#<DataObjectId>" metric for all input DataObjects read by an Action, and calculating "transferPct" metric as factor of 'count main output' / 'count main input'.
Note that "transferPct" could be used by a custom expectation implementation, but in my opinion the metric is more about the Quality of Transformation/Action than the Quality of the Data written to the DataObject. I would rather suggest to check the "transferPct" in an Actions.metricFailCondition.
