### ISSUE TITLE
Spark Update 3.5.0

### ISSUE THREAD

**Issue by ThierryGirod** [smart-data-lake/smart-data-lake#785]
**Is your feature request related to a problem? Please describe.**
I need to have the possibility to build a custom JdbcDialect for Filemaker that can have a custom [select query builder](https://spark.apache.org/docs/latest/api/java/org/apache/spark/sql/jdbc/JdbcSQLQueryBuilder.html).
The [JdbcDialect](https://spark.apache.org/docs/latest/api/java/org/apache/spark/sql/jdbc/JdbcDialect.html) class only supports this behavior since version 3.5.0

**Describe the solution you'd like**
I would like to have sdlb support spark 3.5.0

**Comment by zzeekk** [comment]
Note: Spark 3.5 needs additional add-opens parameter for Java11+: 
"--add-exports java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED"

**Comment by AdiWehrli** [comment]
A little hint: please use Spark 3.5.1 as there was a relevant bugfix [SPARK-45896](https://issues.apache.org/jira/browse/SPARK-45896).
