### ISSUE TITLE
Deduplicate Transformer

### ISSUE THREAD

**Issue by ThierryGirod** [smart-data-lake/smart-data-lake#790]
**Describe the solution you'd like**
I have two projects where the transformer was implemented by the project owner himself using the transformer in combination with a HistorizeAction. So it makes sense to me providing a general approach for this in SDLB.

Because very often you know what the conditions are for duplication detection, the transformer should deduplicates data based on primaryKey columns and a ranking Expression. The transformer is found in the attachment.

[DeduplicateTransformer.txt](https://github.com/smart-data-lake/smart-data-lake/files/14328934/DeduplicateTransformer.txt)

We should discuss if it needs to be a generic transformer or it should stay a spark transformer.

The transformer should have two parameters to pass:
1. List of primary key columns
2. String rankingExpression

The transformer should return deduplicated dataframe based on ranking expression with only unique primary keys

**Comment by iliassoto** [comment]
We also use this transformer in a project, so I also think it's a good idea to make it generally available.

**Comment by zzeekk** [comment]
As you get the actionId as parameter of the transform function, you could lookup primary keys on the actions output DataObject (if its only one output...).
To get the action you can use Environment.instanceRegistry.get(actionId).

That means parameter 1. (List of primary key columns) of the Transformer could be optional.
