### ISSUE TITLE
Pre-/Post SQL for delta tables

### ISSUE THREAD

**Issue by pgruetter** [smart-data-lake/smart-data-lake#791]
**Is your feature request related to a problem? Please describe.**
For JdbcTableDataObjects, we support preRead/postRead and preWrite/postWrite SQL Statements which are very handy. 
The same could be implemented for DeltaLakeTableDataObject.

**Describe the solution you'd like**
Implement the same 4 pre/post read/write SQL Statements on DeltaLakeTableDataObject.

**Comment by zzeekk** [comment]
Good idea. We should try to implement this generically, so that we can add it to DeltaLakeTableDataObject, IcebergTableDataObject and even HiveTableDataObject?
