### ISSUE TITLE
Question: how to configure Hikari settings?

### ISSUE THREAD

**Issue by AdiWehrli** [smart-data-lake/smart-data-lake#794]
Hello together,

Does one know, how we can set Hikari properties for JDBC connection like `connectionTimeout`, `idleTimeout`, `connectionTestQuery` etc.?

Thanks very much in advance.

Kind regards,
Adi

**Comment by pgruetter** [comment]
Hi @AdiWehrli 
Don't know Hikari. But did you try setting the jdbcOptions on the data object?
See https://smartdatalake.ch/json-schema-viewer?schema=sdl-schema-2.6.0-SNAPSHOT.json&path=%5B2%2C12%2C14%5D
Should be possible to set any JDBC options with this parameter.

**Comment by pgruetter** [comment]
.. which gets me thinking: it should be possible to set jdbcOptions on JDBC connections. Any options set on the connection, should be applied each time the connection is used. 
@zzeekk What do you think?

**Comment by ThierryGirod** [comment]
@pgruetter I think we have to pay attention. The point that comes to my mind is that you cannot generalize all jdbc options to the connection. You also have options that are data object related ex. if you specify the query or the dbtable parameter.

**Comment by pgruetter** [comment]
True, there's also considerations like which options you can overwrite in your DataObject that are also defined on the connection level. But I mean in general, would be maybe worth analyzing.

**Comment by AdiWehrli** [comment]
Thanks for the replies. To provide more details: we want to ensure, that a `JdbcTableConnection` can switch between multiple configured DB hosts, if one would suddenly be unavailable. That's the main point here. And we mostly use Hikari in our other applications to ensure this.

As I looked at the [SDL schema](https://smartdatalake.ch/json-schema-viewer/?schema=sdl-schema-2.5.2.json) I recognized, that such properties would not be valid. We have the following valid properties for pooling/initalization in `JdbcTableConnection`:
`maxParallelConnections`
`connectionPoolMaxIdleTimeSec`
`connectionPoolMaxWaitTimeSec`
`connectionInitSql`

But there are no properties to ensure valid connections, as you can see in [HikariCP - Configuration (knobs, baby!)](https://github.com/brettwooldridge/HikariCP#gear-configuration-knobs-baby), are there? 

Maybe the Hikari property `connectionTestQuery` could mean almost the same as SDL property `connectionInitSql`? But I do not suppose so, because Hikari also has a separate `connectionInitSql`:

> `connectionInitSql`: This property sets a SQL statement that will be executed after every new connection creation before adding it to the pool. If this SQL is not valid or throws an exception, it will be treated as a connection failure and the standard retry logic will be followed. Default: none

> `connectionTestQuery`: If your driver supports JDBC4 we strongly recommend not setting this property. This is for "legacy" drivers that do not support the JDBC4 Connection.isValid() API. This is the query that will be executed just before a connection is given to you from the pool to validate that the connection to the database is still alive.

Could at least some of those properties be included in SDL? What do you think?

Thanks very much in advance.

Kind regards,
Adi

**Comment by AdiWehrli** [comment]
Well, I see that `org.apache.commons:commons-pool2:2.11.1` does not have such properties.

**Comment by AdiWehrli** [comment]
I patched the class `JdbcTableConnection` for HikariCP:
```java
  /**
   * <p>Get the connection base on the previously configured URL and credentials (if any)</p>
   * <cite>Patched by Adi Wehrli, 28-FEB-2024</cite>
   * @return the resulting {@link SqlConnection}
   */
  private def getConnection: SqlConnection = {
    Class.forName(driver)
    if (authMode.isDefined) authMode.get match {
      case m: BasicAuthMode => getConnection(url, m.userSecret.resolve(), m.passwordSecret.resolve())
      case _ => throw new IllegalArgumentException(s"${authMode.getClass.getSimpleName} not supported.")
    } else getConnection(url, null, null)
  }

  /**
   * <p>Get an {@link SqlConnection} for the given arguments. If the system property {@code hikaricp.configurationFile} is
   * set then use this file as configuration for a HikariCP connection. Otherwise a 'normal' connection is used.</p>
   * <p>If a HikariCP connection is to be established the {@code url}, {@code url} and {@code url} within the
   * {@code hikaricp.configurationFile} (if any) are overwritten.</p>
   * <cite>Patched by Adi Wehrli, 28-FEB-2024</cite>
   *
   * @param url the JDBC URL for the database connection
   * @param username the username for the database connection
   * @param password the password for the database connection
   * @return the resulting {@link SqlConnection}
   */
  private def getConnection(url: String, username: String, password: String): SqlConnection = {
    if (System.getProperty("hikaricp.configurationFile") != null && new File(System.getProperty("hikaricp.configurationFile")).exists()) {
      val hikariConfig: HikariConfig = new HikariConfig()
      hikariConfig.setJdbcUrl(url)
      hikariConfig.setUsername(username)
      hikariConfig.setPassword(password)
      logger.info(s"HikariCP SQL connection is used with the following configuration: connectionTestQuery=${hikariConfig.getConnectionTestQuery}, "
        + s"maximumPoolSize=${hikariConfig.getMaximumPoolSize}, maxLifetime=${hikariConfig.getMaxLifetime}, "
        + s"validationTimeout=${hikariConfig.getValidationTimeout}, idleTimeout=${hikariConfig.getIdleTimeout}, "
        + s"driverClassName=${hikariConfig.getDriverClassName}")
      new HikariDataSource(hikariConfig).getConnection
    } else {
      logger.info("Normal SQL connection is used")
      DriverManager.getConnection(url, username, password)
    }
  }
```

**Comment by zzeekk** [comment]
Hi @AdiWehrli, thanks for the suggestion.
You are right, the apache common-pool2 does not support testing JDBC connection. Its also not specifically designed for DB Connection, but a generic pool. We use it also in other places, for instance to manage SFTP connections.

If i understand it correctly HikaryCP validates connections before borrowing by executing connectionTestQuery. If the validations fails, the connection is closed and a new one created, which might connect to another db host as configured in the url given.

With your patch you now have two cascaded pools, as the getConnection method is called from the JdbcClientPoolFactory, which is used together with common-pool2. I'm not sure that this behaves the way would like to, as the connection is still cached outside of HikaryCP in common-pool2, and might not be re-created but still fails...

I think the proper way to customize this would be to introduce a configuration for a connectionFactoryClass, which can be used to override the current JdbcClientPoolFactory that is statically called for now.
WDYT?

**Comment by AdiWehrli** [comment]
Thanks, @zzeekk. You catched the case completely. I also thought that this "mixture" between Hikari datasource and Common datasource could be difficult. A connectionFactoryClass surely would be a possible way.

**Comment by zzeekk** [comment]
Hi @AdiWehrli, i created a draft for a new configuration attribute JdbcTableConnection.connectionPoolClassName.
To configure your own ConnectionPool, you could implement a class
class MyJdbcConnectionPool(jdbcTableConnection: JdbcTableConnection) extends ConnectionPool[java.sql.Connection] {
  override def borrowObject: Connection = ???
  override def returnObject(connection: Connection): Unit = ???
}
In the implementation you can access the configuration properties (like url) from JdbcTableConnection, and use JdbcConnectionFactory.getConnection to create jdbc connections according to SDLB standards.

But i see another problem - this is only for JDBC connections used by SDLB on the Driver Node... Spark creates its own JDBC Connections on the Executors using JdbcConnectionProviders. There is no Connection Pool used, this interface has no method to return objects to a "pool". Maybe the connection instance could be wrapped and the close() statement used for returning to a pool. On the other hand if every Spark task on the executor creates a new connection, this would also be kind of failsafe, as the new connection should work normally, as it is not cached in a pool but just newly created.
https://github.com/apache/spark/blob/b0a027ca4f72becad08d0e69d01f23c8caddf621/sql/core/src/main/scala/org/apache/spark/sql/jdbc/README.md

**Comment by AdiWehrli** [comment]
Hello @zzeekk und @pgruetter 

I have found the problem which causes our job to fail if one JDBC host is not available. The situation is like that:
* we have an Oracle JDBC URl which contains an address list with two different hosts
* SDL takes one host from this address list
* after that `JdbcTableDataObject.prepare()` method first executes a test on the connection
* the test fails if the host is not available and a `ConnectionTestException` is thrown (row 151-153 in `JdbcTableDataObject`)
* no further retries on the other host is made, the job fails

A workaround is to change the host sequence in Oracle JDBC URL address list, but this is not satisfactory as our database locations can be switched suddenly.

Maybe this has something to do with the fact that `BaseGenericObjectPool.testOnBorrow` is set to `false` by default?

**Comment by zzeekk** [comment]
Hi @AdiWehrli, i created a new Branch and PR #836 with validateObject method implemented, and a ConnectionPoolConfig case class to configure the properties of the connection pool. Ok for you?
