### ISSUE TITLE
Multiple Jackson Vulnerability Findings 

### ISSUE THREAD

**Issue by SaPaDev** [smart-data-lake/smart-data-lake#803]
**Is your feature request related to a problem? Please describe.**

We had several vulnerability findings regarding jackson dependencies internally. 

**Describe the solution you'd like**
Updating the following repositories in the [sdl-parent](https://github.com/smart-data-lake/smart-data-lake/blob/2.6.0/pom.xml).

-  [ackson-mapper-asl](https://mvnrepository.com/artifact/org.codehaus.jackson/jackson-mapper-asl).
-  [fasterxml.jackson.core](https://mvnrepository.com/artifact/com.fasterxml.jackson.core).

**Additional context**

Possibly more open issues with vulnerability findings.

**Comment by zzeekk** [comment]
Hi @SaPaDev,
Is your finding on the current version 2.6.0?
Actionally jackson-mapper-asl is already excluded in pom.xml 2.6.0 on the relevant places, see https://github.com/smart-data-lake/smart-data-lake/blob/2.6.0/pom.xml#L2911.
And jackson-core is on version 2.14.2, which has no known vulnerabilities, see https://ossindex.sonatype.org/component/pkg:maven/com.fasterxml.jackson.core/jackson-core@2.14.2.
Can you please check your finding and give more details?

**Comment by SaPaDev** [comment]
Hello @zzeekk 

Thank you for the clarification. It seems that our initial finding was based on outdated information. Upon reviewing the provided links, it's evident that jackson-mapper-asl is already excluded in pom.xml 2.6.0 and that jackson-core is on version 2.14.2, which has no known vulnerabilities.

Considering this, it appears that updating to version 2.6.0 on our end should resolve the finding. We will proceed with the update accordingly. 

Based on the information provided, it seems reasonable to resolve the ticket from our end.

**Comment by zzeekk** [comment]
Thanks for clarifying, i'm going to close it then.
