### ISSUE TITLE
Question: is it possible to delete files with SDL?

### ISSUE THREAD

**Issue by AdiWehrli** [smart-data-lake/smart-data-lake#816]
Hello,

We need to delete files/folders from S3 buckets that are older than a specific time. Is this possible with SDL?

Thanks very much in advance.

Kind regards, 
Adi

**Comment by pgruetter** [comment]
Hello @AdiWehrli 
What kind of files are we talking about? Just arbitrary files or files that belong to a DataObject? If it's the latter, then SDL has a housekeepingMode that could help. But it only works on whole partitions at this point.
Other than that, I'm not aware of any method we currently have to cleanup files.

**Comment by AdiWehrli** [comment]
Hello @pgruetter 

Thanks for your reply. I now have created a housekeeping client which uses Hadoop's S3aFileSystem to determine and remove outdated folders.

Kind regards,
Adi
