### ISSUE TITLE
Included spark / hadoop dependencies

### ISSUE THREAD

**Issue by zzeekk** [smart-data-lake/smart-data-lake#83]
Spark / Hadoop dependencies have "compile" scope for now. This means these dependencies are normally included with their version (spark 2.4.4/hadoop 2.6.5) in projects which use the release build. This is good and simple for playing around, but in production most projects have specific spark/hadoop versions they want/need to use (e.g. hadoop 2.6.0-cdh5.16.1). Also when using spark-submit these dependencies are provided... if not excluded in the submitted jar they override the versions which are correct/needed on the cluster.

@pgruetter, @swissrussdev : What's you're opinion on this?

Here an example of the exclusions for spark-submit:
```
		<dependency>
			<groupId>io.smartdatalake</groupId>
			<artifactId>smartdatalake_${scala.minor.version}</artifactId>
			<version>1.0.3-SNAPSHOT</version>
			<scope>compile</scope>
			<exclusions>
				<exclusion>
					<groupId>org.apache.hadoop</groupId>
					<artifactId>hadoop-common_${scala.minor.version}</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.spark</groupId>
					<artifactId>spark-core_${scala.minor.version}</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.spark</groupId>
					<artifactId>spark-sql_${scala.minor.version}</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.spark</groupId>
					<artifactId>spark-catalyst_${scala.minor.version}</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.spark</groupId>
					<artifactId>spark-avro_${scala.minor.version}</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.scala-lang</groupId>
					<artifactId>scala-library</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.scala-lang</groupId>
					<artifactId>scala-reflect</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.scala-lang</groupId>
					<artifactId>scala-compiler</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
```

**Comment by swissrussdev** [comment]
Good catch - docs are fairly clear on this, they should be listed as provided. 

https://spark.apache.org/docs/latest/submitting-applications.html

**Comment by zzeekk** [comment]
I discussed further maven best practices with Dominik. 

1) We should definitely set scope to provided, like that the fat-jar will no longer include spark dependencies., but we could create a profile to change the scope to compile to build the fat-jar-with-spark.

2) We should try maven-enforcer-plugin with option dependencyConvergence to check for dependency version conflicts.

3) We should use a dependencyManagement section to clean up dependency version conflicts between the dependencies with scope!=provided.

4) We could create a separate smartdatalake-buildtools pom only artifact which can be included with scope=import and type=pom to get basic scala dependencies, log4j2 and default plugins configuration (unit/integration-tests, shade plugin) for starting new projects faster.

**Comment by zzeekk** [comment]
Using scope "provided" doesn't work for the normal smartdatalake artifact jar, as these dependencies are then no longer inherited by projects using it, e.g. sdl-examples...

**Comment by zzeekk** [comment]
We should import dependencyManagement from spark-parent

**Comment by zzeekk** [comment]
I created a draft for a better pom, modularizatiom and how to include smartdatalake in potential applications.
In sdl-parent we
- import dependencyManagement from spark-parent
- refine dependencyManagement for our purpose
- copied properties from spark-parent
- refined properties for our purpose
- created pluginMangement with basic configuration of maven plugins
In the modules like sdl-core or sdl-kafka we
- use spark-parent as parent
- add dependencies using dependencyManagement from sdl-parent to clean up any conflicting versions
- add plugins using pluginManagement
In applications like sdl-examples we
- use spark-parent as parent
- have a dependency to sdl-core and any other sdl-* modules using depencyMangement from sdl-parent to clean up any conflicting version
- use properties and exclusions to tune versions as needed (e.g. exchanging log4j V1.2 with log4j V2.)
See branches:
- https://github.com/smart-data-lake/smart-data-lake/tree/feature/83-improve-pom
- https://github.com/smart-data-lake/sdl-examples/tree/feature/83-improve-pom
