### ISSUE TITLE
sdl-parent 2.6.1 not yet available?

### ISSUE THREAD

**Issue by AdiWehrli** [smart-data-lake/smart-data-lake#842]
Hello together,

It seems that `sdl-parent` version 2.6.1 is not yet available on any Maven repository. 

Kind regards,
Adi Wehrli

**Comment by pgruetter** [comment]
Hell @AdiWehrli 
Thanks for the heads-up, will check that!

**Comment by pgruetter** [comment]
You are right, release 2.6.1 wasn't approved for central deployment yet. Just did it now, usually takes a few hours to synchronize.
Sorry about that.

**Comment by AdiWehrli** [comment]
The SDL dependencies for version 2.6.1 are now available. Thanks very much, @pgruetter 😃
