### ISSUE TITLE
Add User authentication to SDLB

### ISSUE THREAD

**Issue by dnLeiting** [smart-data-lake/smart-data-lake#859]
**Is your feature request related to a problem? Please describe.**
Currently, the SDLB provides the option to upload Configs, Config-Stats, Config-Schemas, and Statefiles to the SDLB-Backend.
However, since the SDLB-Backend Endpoints require a token to authenticate a user, the current SDLB implementation is outdated.
Thus, the SDLB implementation needs to be extended to include a means of authentication in each request to the SDLB-Backend.
Thereby, the authentication process follows two main steps:

1. A JWT token is fetched based on a username and password.
2. The provided JWT token is added as "Authorization" in the header of each request.

**Describe the solution you'd like**
To enable the SDLB to follow the described authorization procedure, additional input parameters are required.
- username
- password
- AWS client-id
- Cognito URL

The username and password can belong to a Technical User or a Standard User, since the authentication endpoint is provided as part of the parameters.
Hence, the authentication process agnostic of different Cognito setups, is guaranteed.

**Additional context**
The required changes are located in the [sdl-lang](https://github.com/smart-data-lake/smart-data-lake/tree/develop-spark3/sdl-lang) module.
For the implementation the aws-java-sdk-cognitoidp dependency could be used.
An example implementation can be found in the following medium blog post.
https://medium.com/@warrenferns/integrate-java-with-aws-cognito-developer-tutorial-679e6e608951

**Comment by zzeekk** [comment]
I dont like pulling aws-java-sdk dependency always into SDLB. Looks like OAuth2 authentication. 
We could use standard http calls. It might be easier to implement with sttp library, see also #823 and https://sttp.softwaremill.com/en/latest/requests/authentication.html#oauth2

**Comment by zzeekk** [comment]
Note that a refactoring of AuthModes is included in the PR to allow direct implementation of AuthModes by implementing ParsableFromConfig instead of using sealed trait.

Also Keycloak AuthMode was removed, as it is not used and has extensive dependencies.

**Comment by zzeekk** [comment]
A sample configuration to connect to the SDLB AWS SaaS UI looks as follows:
```
global {
  uiBackend {
    baseUrl = "https://nn92uqy13e.execute-api.eu-central-1.amazonaws.com/DEV/api/v1"
    tenant = PrivateTenant
    repo = int-testing
    env = std
    authMode {
      type = AWSUserPwdAuthMode
      region = eu-central-1
      userPool = sdlb-ui
      useIdToken = true
      clientId = "###FILE#ui-auth;clientId###"
      user = "###FILE#ui-auth;user###"
      password = "###FILE#ui-auth;pwd###"
    }
  }
}
```
