### ISSUE TITLE
SubFeed metrics keep input values if skipped

### ISSUE THREAD

**Issue by zzeekk** [smart-data-lake/smart-data-lake#872]
**Describe the bug**
Output SubFeeds keep metrics from Input SubFeeds when action is Skipped

**To Reproduce**
2 Actions, second is skipped because there is no-data.
When debugging it seems that SubFeed metrics are not cleared, but keep the value from the Input SubFeed, e.g. from the previous Actions output SubFeed.

When an Action is executed successfully or fails because of expectation validation failure, each output SubFeeds metrics are overwritten. But if the Action is skipped this seems not to be the case.

**Expected behavior**
Output SubFeeds metrics are cleared before execution is started.

**Comment by zzeekk** [comment]
This was just an internal problem, not affecting metrics in state or logs, see new test case which already worked without any changes.

**Comment by Geheiner** [comment]
Can you elaborate on that internal problem? Maybe you can show it to me sometime. Was this bug triggered by #873 ?

**Comment by zzeekk** [comment]
> Can you elaborate on that internal problem? Maybe you can show it to me sometime. Was this bug triggered by #873 ?

I was just confused when debugging that there where metrics on the SubFeeds, also when they were skipped. It turned out that the metrics were copied from the input subfeed. It was just an internal problem, as they got correctly overwritten later in the process. But fixing this makes the implementation more consistent.
