### ISSUE TITLE
Question: does SDL 2.7.0 work with Spark 3.5.2?

### ISSUE THREAD

**Issue by AdiWehrli** [smart-data-lake/smart-data-lake#881]
Hello together,

Does SDL 2.7.0 already work with Spark 3.5.2?

Thanks in advance.

Kind regards, 
Adi Wehrli

**Comment by zzeekk** [comment]
Hi @Adi
Yes, SDL 2.7.x is compatible with Spark 3.5.x.
We just updated current branch develop-spark3 (2.7.1-SNAPSHOT) to Spark 3.5.2, all tests passed.
