### ISSUE TITLE
CSV export to one single file

### ISSUE THREAD

**Issue by PMuellerELCA** [smart-data-lake/smart-data-lake#893]
If you write data with a CsvFileDataObject it writes the data with spark default behavior in a separate folder with possibly multiple csv files - one for each worker. While this is the normal behavior of Spark there should be an option to write just a single file.

When this option is active, the writing process should be extended with the following process:

Concentrate all data to one worker - coalesce(1)
Write the CSV file with Spark standard process
Move the one CSV file from the newly created folder to the parent folder
Delete the folder.
Rename the file to the specified name

**Comment by zzeekk** [comment]
Yes we can - try the following
```
{ 
  type = CsvFileDataObject
  ...
  sparkRepartition {
    numberOfTasksPerPartition = 1
    filename = data.csv
  }
}
```

**Comment by PMuellerELCA** [comment]
Thanks, it works.
