### ISSUE TITLE
JdbcTableDataObject: isTableExisting does not work on Oracle databases

### ISSUE THREAD

**Issue by MarkusRothSBB** [smart-data-lake/smart-data-lake#91]
isTableExisting on JdbcTableDataObject uses INFORMATION_SCHEMA.TABLES to check if a table exists in the prepare step of the action. This does not work on Oracle databases, because that view does not exists - in the Oracle world, table metadata is accessible with the view [ALL_TABLES](https://docs.oracle.com/database/121/REFRN/GUID-6823CD28-0681-468E-950B-966C6F71325D.htm).

**Comment by zzeekk** [comment]
@MarkusRothSBB Can you test branch https://github.com/smart-data-lake/smart-data-lake/compare/bugfix/91-jdbc-oracle-catalog with Oracle?

**Comment by MarkusRothSBB** [comment]
@zzeekk Thanks for the fix! I tested it on our Oracle database and it works perfectly.
