### ISSUE TITLE
Add filter to ignore invalid Kafka messages

### ISSUE THREAD

**Issue by AdiWehrli** [smart-data-lake/smart-data-lake#915]
**Is your feature request related to a problem? Please describe.**
Messages in a Kafka topic can be null or an array of byte with null elements.

**Describe the solution you'd like**
Those messages should be filtered out.

**Comment by AdiWehrli** [comment]
Maybe we could accomplish this with adjustment of method `convertToReadDataFrame()` in `KafkaTopicDataObject` like this:
```scala
  private def convertToReadDataFrame(dfRaw: DataFrame): DataFrame = {
    import DataFrameUtil._

    // convert key & value
    val colsToSelect = ((if (selectCols.nonEmpty) selectCols else Seq("kafka.*")) ++ partitions).distinct.map(col)
    logger.info(s"Filtering dataFrame 'dfRaw' for incorrect values")
    val dfWithoutIncorrectValues = dfRaw
      .withColumn("key", col("key"))
      .withColumn("value", col("value"))
      .where(col("value").isNotNull && len(col("value")) > 0)
      .as("kafka-filter-incorrect-values")
      .withOptionalColumn(datePartitionCol.map(_.colName), udfFormatPartition(col("timestamp")))
    logger.info(s"Converting filtered dataFrame keys/values from Kafka")
    val df = dfWithoutIncorrectValues
      .withColumn("key", convertFromKafka(keyType, col("key"), SubjectType.key, keySchema))
      .withColumn("value", convertFromKafka(valueType, col("value"), SubjectType.value, valueSchema))
      .as("kafka")
      .withOptionalColumn(datePartitionCol.map(_.colName), udfFormatPartition(col("timestamp")))
      .select(colsToSelect:_*)
    // return
    df
  }
```

What do you think, @zzeekk?

**Comment by zzeekk** [comment]
Hi @AdiWehrli, these are probably tombstone messages, see also https://medium.com/@damienthomlutz/deleting-records-in-kafka-aka-tombstones-651114655a16

I suggest to *not* apply the convertFromKafka conversion if a value is null (or empty array), but i would not filter them out by default. This should be done in an action/transformer later. Otherwise tombstone messages are lost for cases where they would be relevant.

**Comment by AdiWehrli** [comment]
Hello @zzeekk 

Thanks for your response. I want to mention, that the topic's cleanup policy is not 'compact'.

Kind regards,
Adi

**Comment by zzeekk** [comment]
Hi @AdiWehrli, yes, but this is independent of the topic policy is 'compact'.
There is a client writing a tombstone into the topic (for whatever reason...). The consumers will receive the tombstone message.
In the current code the convertFromKafka method crashed for this message. We fix this by passing through the value=null message without applying convertFromKafka.

The Action/Transformer has then to decide what to do with the tombstone message - filter, pass-through, any special logic...

Does this solution fit for your case?

**Comment by AdiWehrli** [comment]
Hello @zzeekk 

Thanks for your change. This looks quite ok. Could you then please also provide an example for filtering?

Kind regards

**Comment by zzeekk** [comment]
@AdiWehrli: i dont know exactly if your Action already has existing transformers, but if there are no transformers you could add a FilterTransformer as follows:
```
actions {
  copy1 {
    type = CopyAction
    ...
    transformers [{
      type = FilterTransformer
      filterClause = "value is not null"
    }]
    ...
  }
```

**Comment by AdiWehrli** [comment]
Thanks very much, @zzeekk, for the example.

Now have nice festive days and kind regards,
Adi
