### ISSUE TITLE
Make Historize/DeduplicatAction generic

### ISSUE THREAD

**Issue by zzeekk** [smart-data-lake/smart-data-lake#916]
**Is your feature request related to a problem? Please describe.**
For now Historize/DeduplicatAction is only implemented for SubFeedType Spark.
It should also support other SubFeedTypes.

**Describe the solution you'd like**
Implement Historize/DeduplicatAction generically, see TODOs in corresponding Scala files.

**Comment by Geheiner** [comment]
Basically, https://github.com/smart-data-lake/smart-data-lake/pull/924 added support for SnowparkSubfeed and prepared for future support of non-dataframe subfeeds, right?
