### ISSUE TITLE
Make metric gathering optional

### ISSUE THREAD

**Issue by pgruetter** [smart-data-lake/smart-data-lake#917]
**Is your feature request related to a problem? Please describe.**
We have one specific case, where metric gathering doesn't work correctly within the 10 second timeout:
```
Root cause is 'SparkJobNotEndedException: SparkStageMetricsListener didn't get onJobEnd notification for jobIds=99,100 within timeout of 10 seconds.'
```
Caused probably by the function waitForLastMetrics [here](https://github.com/smart-data-lake/smart-data-lake/blob/a49649af50271f6a97c9e5170b08ff1fa80b0a9d/sdl-core/src/main/scala/io/smartdatalake/metrics/SparkStageMetricsListener.scala#L139).

This throws an exception and causes the whole SDLB run to fail.

**Describe the solution you'd like**
By default, we should not throw an exception in these cases so SDLB can finish successfully. Just log a warning instead.
We can add a global env config to change the behavior, i.e. `ThrowExceptionOnMetricError`

**Comment by zzeekk** [comment]
New implementation is: by default a warning is logged. Going back to throwing an exception can be configured using Environment.throwExceptionOnSparkListenerError.
