### ISSUE TITLE
JdbcTableDataObject: Query passed to dbtable property rather than query property when creating DataFrame

### ISSUE THREAD

**Issue by MarkusRothSBB** [smart-data-lake/smart-data-lake#92]
It is possible to define a query for a table (query field on case class Table). In getDataFrame on JdbcTableDataObject, this query is read and passed to spark to create the DataFrame. However, it is passed to the [dbtable property, rather than the query property](https://spark.apache.org/docs/latest/sql-data-sources-jdbc.html). This makes Oracle interpret the query as a table name, leading to an error.

The following code works, leading Oracle to execute the query and return the results:

 ```
override def getDataFrame(partitionValues: Seq[PartitionValues] = Seq())(implicit session: SparkSession): DataFrame = {
    val queryOrTable = table.query match {
      case Some(query) => ("query", query)
      case None => ("dbtable", table.fullName)
    }
    val df = session.read.format("jdbc")
      .options(
        Map("url" -> connection.url,
          "driver" -> connection.driver,
          "fetchSize" -> jdbcFetchSize.toString))
      .options(connection.getAuthModeSparkOptions)
      .options(Map(queryOrTable))
      .load()
    validateSchemaMin(df)
    df.colNamesLowercase
  }

```

**Comment by zzeekk** [comment]
Good one, seems this is possible since Spark 2.4.0.

**Comment by swissrussdev** [comment]
True, but there are some limitations (see docs). Doesn't an implementation which passes  "(<query>) sdl-query-alias" do the same thing but with the added option of specifying a partitioning column for parallel execution?
