### ISSUE TITLE
Compressed writing to Kafka

### ISSUE THREAD

**Issue by AdiWehrli** [smart-data-lake/smart-data-lake#934]
Hello together

Is it possible to tell SDL that it should write compressed to a Kafka topic? Something like this perhaps?
```
       options {
          ...
          "kafka.compression.type" = "gzip"
        }
```

Well, this does not work.

Thanks very much in advance.

Kind regards,
Adi

**Comment by zzeekk** [comment]
Hi @AdiWehrli, yes i would suggest the same. Like that the option should be used by Spark to create the Kafka producer.

**Comment by AdiWehrli** [comment]
So, how do I configure this now? Within the `sparkOptions`?

**Comment by zzeekk** [comment]
Just as you proposed:
```
dataObjects {
  kafka1 {
    type = KafkaTopicDataObject
    ...
    options {
      "kafka.compression.type" = "gzip"
    }
  }
}
```
Let's try...

**Comment by AdiWehrli** [comment]
It did not work:
`Caused by: org.apache.kafka.common.errors.RecordTooLargeException: The message is 2832891 bytes when serialized which is larger than 1048576, which is the value of the max.request.size configuration.`

**Comment by AdiWehrli** [comment]
And if I set the option `kafka.max.request.size` we will get the following error:
`Caused by: org.apache.kafka.common.errors.RecordTooLargeException: The request included a message larger than the max message size the server will accept.`

And we are not allowed to increase the size of the topic...

**Comment by AdiWehrli** [comment]
Unfortunately the tester had reduced input files sizes, so we can't reproduce this anymore. My last intention was to add the property to the options of the `KafkaConnection` object:
```
        options {
          "kafka.compression.type" = "gzip"
        }
```

At least the process seemed to have accepted this but I cannot prove whether or not this would have been the solution.
