### ISSUE TITLE
Handle Code Smells

### ISSUE THREAD

**Issue by pgruetter** [smart-data-lake/smart-data-lake#99]
With sonarcloud, a list of code smells was generated:
https://sonarcloud.io/project/issues?id=smart-data-lake_smart-data-lake&resolved=false&types=CODE_SMELL

There is some valuable input here, we should go through that list and either solve the code smells or mark them as false-positive / wont-fix.

**Comment by zzeekk** [comment]
@pgruetter : can we exclude unit tests from the code to be inspected? see "sonar.test.exclusions" on https://docs.sonarqube.org/latest/project-administration/narrowing-the-focus/.

**Comment by pgruetter** [comment]
> can we exclude unit tests from the code to be inspected? 

Yes, good idea! Agree that it doesn't make sense to check for duplications in the unit test code blocks i.e. 
Excluded the whole src/test path.
